### ISSUE TITLE
ld: framework not found FXKeychain 

### ISSUE THREAD

**Issue by kumarSC** [Subito-it/SBTUITestTunnel#1]
Hey @tcamin ,

I have been trying to integrate this library to mock XCode UI test and followed the instructions here, https://github.com/Subito-it/SBTUITestTunnel#installation-cocoapods.I am working on a Swift project so I have imported the header files in *-Bridging-Header.h .When I try to build the project , it fails saying 
```
ld: framework not found FXKeychain
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I can confirm that FXKeychain (1.5.3) is getting downloaded when I run `pod install`. Not sure what I am missing here.Some input might bail me out.

**Comment by tcamin** [comment]
Hi there! Thanks for reaching out.

What version of cocoapods are you using? Given that you're working on a Swift project you may consider using `use_frameworks!` in your Podfile which avoid you with the hassle of importing headers in the bridging headers.

What about the sample project shipped with the library? Have you tried to compile that one?

**Comment by tcamin** [comment]
Closing issue due to no response. You should try again with the latest version and check out the updated README file.
