### ISSUE TITLE
Undefined symbols for architecture xxx:   "_OBJC_CLASS_$_SBTUITestTunnelServer"

### ISSUE THREAD

**Issue by clementRoulland** [Subito-it/SBTUITestTunnel#10]
Hi, I try to use your library but i got an error when i follow your tutorial on README.md.
```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SBTUITestTunnelServer", referenced from:
      type metadata accessor for __ObjC.SBTUITestTunnelServer in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have the same issue on all simulators and devices.

More informations on my implementation : 
* XCode 8.0
* Swift 2.3
* iOS 10
* Pods 1.1.0.rc.2 and Runpath Search Paths set
* podfile:
```
target 'XXX' do
    pod 'SBTUITestTunnel/Server',   '~> 1.0'
end

target 'XXXTests' do
    
end

target 'XXXUITests' do
    pod 'SBTUITestTunnel/Client', '~> 1.0'
end
```
* AppDelegate
```
import UIKit
import SBTUITestTunnel

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?
    var appInitializer: AppInitializer?
    
    override class func initialize() {
        SBTUITestTunnelServer.takeOff()
        super.initialize()
    }

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        return true
    }

}
```

**Comment by tcamin** [comment]
A part from the missing `use_frameworks!`  in the Podfile, which has nothing to do with the error you're reporting everything looks ok.

I did a quick test with cocoapods 1.1.0rc3 and everything works as expected. You might try a `pod deintegrate; pod install` and see if that fixes your issue.

**Comment by YannickSteph** [comment]
Hi, 
I have the same error,
I used pod deintegrate and pod install and the error is always.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SBTUITestTunnelServer", referenced from:
      type metadata accessor for __ObjC.SBTUITestTunnelServer in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tcamin** [comment]
What version of Xcode? What version of cocoapods? If it's a sample app can you upload it somewhere so I can check it out?

**Comment by YannickSteph** [comment]
XCode 8.0
Swift 2.3
iOS 10
Pods 1.1.0.rc.2 and Runpath Search Paths set

**Comment by tcamin** [comment]
> The behavior is strange, library import running. 

Does it mean that the project compiles but throws that error when running the app?

**Comment by tcamin** [comment]
The target/build configuration you're running does not define the DEBUG pre processor macro.

I've updated the documentation to highlight this issue, please review the new "Application target" and "DEBUG pre-processor macro" paragraphs.

**Comment by AboulEinein** [comment]
Hello, I'm having the same issue with Xcode 13.1

I've followed the instructions but with no luck
