### ISSUE TITLE
Xcode 12 Compilation Errors

### ISSUE THREAD

**Issue by charleshberlin** [Subito-it/SBTUITestTunnel#102]
I'm updating our app to work with iOS14 on XCode12 and I'm not able to compile any more, I'm getting the error "No such module 'SBTUITestTunnelClient'".  I've been using SBTUITestTunnel for a couple years now (very happy with it btw) and it still works on Xcode11 but will not compile in Xcode12.

Cocoapods version 1.9.3
SBTUITestTunnel 6.5.0
Xcode 12.0
iOS 14.0

Abbreviated Pod File:

use_frameworks!

target 'App' do
   ...
    pod 'SBTUITestTunnelServer'
    pod 'GCDWebServer', :inhibit_warnings => true
end

target 'App-UITests' do
  pod 'SBTUITestTunnelClient'
end

**Comment by tcamin** [comment]
Did you try compiling the sample project compile? It worls fine here with the latest version of Xcode.

That error seems more like an issue with your CocoaPods setup. Is the `]` after pod 'SBTUITestTunnelClient' a  typo?

**Comment by charleshberlin** [comment]
![image](https://user-images.githubusercontent.com/7430549/93911036-e219e880-fccf-11ea-8197-0dbc8e787696.png)
 
Similar issue running the example, and yes the ']' was a typo

**Comment by charleshberlin** [comment]
I saw that cocoapods had fixed some Xcode 12 bugs, so I updated to the newest release candidate (1.10.0.rc.1) and I got a different error now.

![image](https://user-images.githubusercontent.com/7430549/93916052-ef86a100-fcd6-11ea-96dc-cdcc56279e61.png)

**Comment by tcamin** [comment]
On the sample project did you open the SBTUITestTunnel.xcodeproj or SBTUITestTunnel.xcworkspace file?

I tried again with CP  1.10.0.rc.1 and everything compiled fine.

**Comment by tcamin** [comment]
In the meantime I released a new version with a few changes that I made back in August, some Xcode 12 related. Let me know if it solved your problem.

**Comment by charleshberlin** [comment]
Unfortunately no, I updated all my pods and I'm still back to the original problem of "No such module 'SBTUITestTunnelClient'".

I even tried to update my pod file to look like the sample by including the Server and Common pods in both.

**Comment by charleshberlin** [comment]
Ok i got it working now, was comparing my build settings to the project and saw that build active architectures only was set to No.  So some combination of updating to 6.5.1, adding Server and Common in both targets, and setting build active architectures only to no fixed it.

Thanks for your help
