### ISSUE TITLE
Unable to compile application with SBT enabled

### ISSUE THREAD

**Issue by svankeswaram** [Subito-it/SBTUITestTunnel#105]
I am having issues with SBT. 
Xcode 11.7
Used the latest cocopod version and latest Master version.  Still getting the below issue.
Is there any way to fix the issue please?

![Screenshot 2020-11-06 at 21 18 34](https://user-images.githubusercontent.com/32909489/98415698-abc4dc80-2075-11eb-958b-c6d46c309ab2.png)

**Comment by tcamin** [comment]
Hi, did you try running UI tests in the sample project of the repo. I just tried and it is working.
