### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by akshitzaveri** [Subito-it/SBTUITestTunnel#109]
These are the installation steps followed

### Podfile
```
target 'APP_TARGET' do
  use_frameworks!
  ......
  ......
  ......
  pod 'SBTUITestTunnelServer'
  pod 'GCDWebServer', :inhibit_warnings => true
  
  target 'APP_TARGETUITests' do
    # Pods for UI testing
    pod 'SBTUITestTunnelClient'
  end
end
```

### Preprocessor macros
As we can see below, it has `DEBUG=1`
<img width="583" alt="Screenshot 2020-12-02 at 08 41 12" src="https://user-images.githubusercontent.com/6559898/100823396-2537cb00-347a-11eb-8e85-6429f32cc7c0.png">

### Architectures
<img width="542" alt="Screenshot 2020-12-02 at 08 42 31" src="https://user-images.githubusercontent.com/6559898/100823502-531d0f80-347a-11eb-9bfb-8c6a406d13e0.png">

### AppDelegate
```
#if DEBUG
   import SBTUITestTunnelServer
#endif

#if DEBUG
   SBTUITestTunnelServer.takeOff() // As soon as I uncomment this line, the project does not compile
#endif
```

### Error
<img width="587" alt="Screenshot 2020-12-02 at 08 38 25" src="https://user-images.githubusercontent.com/6559898/100823184-c2deca80-3479-11eb-8c92-300dac74c0d0.png">

**Comment by tcamin** [comment]
Hi, sorry for the late reply.

You should not nest the ui test target in the app targe but instead rewrite the podfile as follows

```
use_frameworks!

target 'APP_TARGET' do
  ......
  ......
  ......
  pod 'SBTUITestTunnelServer'
  pod 'GCDWebServer', :inhibit_warnings => true
end

target 'APP_TARGETUITests' do
  # Pods for UI testing
  pod 'SBTUITestTunnelClient'
end
```

**Comment by kwstasna** [comment]
If anyone gets the following error 

Multiple commands produce '/Users/username/Library/Developer/Xcode/DerivedData/AppName-gwuwaiotjooonicpuxwdrfzuslva/Build/Intermediates.noindex/ArchiveIntermediates/AppName/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework':
1) Target 'SBTUITestTunnel-Client' has create directory command with output '/Users/username/Library/Developer/Xcode/DerivedData/AppName-gwuwaiotjooonicpuxwdrfzuslva/Build/Intermediates.noindex/ArchiveIntermediates/AppName/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework'
2) Target 'SBTUITestTunnel-Server' has create directory command with output '/Users/username/Library/Developer/Xcode/DerivedData/AppName-gwuwaiotjooonicpuxwdrfzuslva/Build/Intermediates.noindex/ArchiveIntermediates/AppName/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework'

the solution of @tcamin  worked for us. Thanks a lot both of you @tcamin and @akshitzaveri !
