### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by francybiga** [Subito-it/SBTUITestTunnel#110]
I was investigating what was needed to add Swift Package Manager support and I found out that `GCDWebServer` (which is a `SBTUITestTunnelServer` dependency) still lacks SPM support. A [pull request](https://github.com/swisspol/GCDWebServer/pull/516) has been opened to add it but it's hasn't been merged yet. 
We could fork `GCDWebServer` to integrate the PR to enable SPM support for `SBTUITestTunnel`.

**Comment by tcamin** [comment]
Support to SPM added in #115
