### ISSUE TITLE
Location manager stubbing issue

### ISSUE THREAD

**Issue by anastasia-sviatokha** [Subito-it/SBTUITestTunnel#111]
Hi,

Thanks for this library, I’ve been using it for a long time!

However, I’m unable to properly stub `CLLocationManager` (the goal is for the authorization status to be `.authorizedAlways` to avoid the location access dialog in UI tests).

So, I just enable stubbing in test setup:
&nbsp;&nbsp;`app.coreLocationStubEnabled(true)`

Once my app is launched, the `CLLocationManager` `authorizationStatus` is `.authorizedAlways`, but then the app gets stuck on `startUpdatingLocation()` while trying to obtain the current location data and never calls the `locationManager(_:didUpdateLocations:)` method.

I only managed to make it work when I updated the `swz_startUpdatingLocation` swizzled method to trigger location updates like:

```
- (void)swz_startUpdatingLocation
{
    CLLocationDegrees latitude = 50.058938;
    CLLocationDegrees longitude = 19.919272;
    CLLocation *locationsData = [[CLLocation alloc] initWithLatitude:latitude longitude:longitude];
    NSArray *locations = @[locationsData];
 
    for (CLLocationManager *locationManager in _instanceHashTable.keyEnumerator.allObjects) {
        [locationManager.stubbedDelegate locationManager:locationManager didUpdateLocations:locations];
    }
}
```

Could you please help me with this problem?

**Comment by tcamin** [comment]
Did you try forcing a location update? https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md#trigger-location-updates

**Comment by anastasia-sviatokha** [comment]
@tcamin Thanks for your reply. Yes, I tried forcing location update, but unfortunately it didn't solve the issue. And I think the problem is in our implementation of the location manager. So, I'm closing this issue.
