### ISSUE TITLE
Support Mocktail

### ISSUE THREAD

**Issue by tspop** [Subito-it/SBTUITestTunnel#12]
I found Mocktail to be a very useful format when building stubs for UI tests.
https://github.com/puls/objc-mocktail

OHHTTPStubs supports it.

PS: Your library is a brilliant solution to UITesting's limitations.

**Comment by tcamin** [comment]
I took a brief look at the format. It looks interesting however at this stage I prefer to keep the stubbing alternatives as simple as possible.

If you strongly dependent on the Mocktail files you may try to add a category that parses the files creating `stubRequestsMatching`'s accordingly.
