### ISSUE TITLE
v8.0.0 Introduces private API that is not removed from release builds

### ISSUE THREAD

**Issue by JARinteractive** [Subito-it/SBTUITestTunnel#121]
DetoxIPC uses Apple private API resulting in rejections from app review.

> ITMS-90338: Non-public API usage - The app references non-public symbols in _app name_: `__Block_signature, ___NSMakeSpecialForwardingCaptureBlock`. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

**Comment by tcamin** [comment]
Could you try the `hotfix/redirects` branch? It contains changes that should address the issue. My suggestion is however to avoid mixing production code with testing one by creating for example a separate target for AppStore submissions which does not include the tunnel library

**Comment by shoaibsadanaut** [comment]
I have tested and it is fixed in 8.1.0

**Comment by ccornelis** [comment]
We ran into the above issue when submitting our app to Apple yesterday (using the master branch):

`The app references non-public symbols in 'appname': ___NSMakeSpecialForwardingCaptureBlock`

Can this be fixed? Or is there a way to embed the SBTUITestTunnelServer framework only for debug builds?
I prefer not to create a new app target just for App Store builds.

**Comment by tcamin** [comment]
Hi! As mentioned in the [setup docs](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Setup.md#-important-please-read) you should ensure not to ship the library during submission. The best option is to have a separate target for submission, but if this is not viable you could ensure to strip the tunnel integration (from the Podfile or Package.swift) before starting the build process. provided that you wrapped everything in #if DEBUG as suggested.

**Comment by ChandanDeshmukh** [comment]
Hi!. What if we are also shipping Debug build to Appstore connect?

**Comment by ChandanDeshmukh** [comment]
Hi!. What if we are also distributing the debug builds to App Store Connect to be available for test flight testing?
