### ISSUE TITLE
ipcProxy performCommandWithParameters hangs while pinging rootProxy 

### ISSUE THREAD

**Issue by rsriz** [Subito-it/SBTUITestTunnel#123]
I tried to update to 8.2.0 version from 6.6.4. While I was testing the migration to new version, I faced issue when performing custom commands after launching the tunnel, I see that sometimes [ipcProxy performCommandWithParameters hangs while pinging rootProxy](https://github.com/Subito-it/SBTUITestTunnel/blob/dd6f403a9f2142152218e960ca33729ca876fa3e/Sources/SBTUITestTunnelCommon/DetoxIPC/_DTXIPCDistantObject.m#L106) (didEndWaiting is always NO, so the loop is infinite)

**Comment by tcamin** [comment]
Can you replicate this in a sample project so that I can take a look? We use custom commands and they work both with IPC and http tunnelling.

**Comment by tcamin** [comment]
Can this be closed?
