### ISSUE TITLE
Stubbing API is not working as expected

### ISSUE THREAD

**Issue by msalmanST** [Subito-it/SBTUITestTunnel#124]
Hi,
I am stubbing one of my api to mimic some of the possible responses from server, what I found event though I do get the stubbed response from network but my orignal API does gets called and I am getting the http response code from the orignal server instead of the stubbed http response code. Below is the code I am testing

> app.stubRequests(

                matching: SBTRequestMatch(url:  url,
                                          method: "POST",
                                          requestHeaders: headers),
                response: SBTStubResponse(response: stubbedResponseJson, returnCode: 500))

What I notice that my network manager does not receive 500 http code as I mentioned in the stub instead it is showing the actual response code returned from the orignal server.

1. Should the orignal API be called in this scenario ( I wan't expecting this as we are doign stubbing so my orignal server should never be called.)
2. I should get the stubbed response data (it is working fine)
3. I should also get the stubbed http code (it is not working as expected as the orignal API gets called)

**Comment by tcamin** [comment]
Could you share a sample project that replicates the issue?

When you stub you should not see the request being performed, so your experiencing something unexpected.

**Comment by msalmanST** [comment]
Hi @tcamin , I created a test project and it was working fine there, so now I am looking in the implementation in my main project to find the root cause of the issue I am facing.

Thanks.

**Comment by tcamin** [comment]
Could you share how you solved your issue?

**Comment by msalmanST** [comment]
What I found is while adding stub I was adding empty headers map and it was causing this issue, after removing it things work fine.
