### ISSUE TITLE
Unable to access new extensions

### ISSUE THREAD

**Issue by rfodge** [Subito-it/SBTUITestTunnel#125]
Hello,

We are trying to upgrade from 6.6.4 to the latest version of 8.0.2.  I am seeing errors saying "Argument passed to call that takes no arguments" for functions like `SBTStubResponse(fileNamed: fileName)`.  I see that the init methods are now in extensions wrapped in the macro block like:
```
#if DEBUG || ENABLE_UITUNNEL
public extension SBTStubResponse {
    convenience init(response: Any, headers: [String: String]? = nil, contentType: String? = nil, returnCode: Int? = nil, responseTime: TimeInterval? = nil, activeIterations: Int = 0) {
        self.init(_response: response as! NSObject, _headers: headers, _contentType: contentType, _returnCode: returnCode ?? -1, _responseTime: responseTime ?? NSTimeIntervalSince1970, _activeIterations: activeIterations)
    }

    convenience init(fileNamed: String, headers: [String: String]? = nil, returnCode: Int? = nil, responseTime: TimeInterval? = nil, activeIterations: Int = 0) {
        self.init(_fileNamed: fileNamed, _headers: headers, _returnCode: returnCode ?? -1, _responseTime: responseTime ?? NSTimeIntervalSince1970, _activeIterations: activeIterations)
    }
}
#endif
```

If I comment out the if/end if lines then my code is able to recognize the function calls like `SBTStubResponse(fileNamed: fileName) `successfully, so i know i must be missing something related to this, however, i'm not sure what since it worked in version 6.6.4. 

In our POD file, we have:
```
pod 'GCDWebServer', '~> 3.5.4'
pod 'SBTUITestTunnelClient', '~> 8.2.0'
pod 'SBTUITestTunnelCommon', '~> 8.2.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'UI-TESTS' || config.name == 'UI-TESTS-LOCAL'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1', 'ENABLE_UITUNNEL_SWIZZLING=1']
            end
        end
    end
end
```

Is there something else we need to update or add for this now? 

I do see it showing up here under preprocessor macros:
<img width="642" alt="Screen Shot 2021-11-04 at 12 29 35 PM" src="https://user-images.githubusercontent.com/11653643/140379826-3478e810-c362-4949-b21c-0203590c540d.png">

**Comment by tcamin** [comment]
You should also add
 `config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "DEBUG"`

**Comment by rfodge** [comment]
This worked, thank you so much for the fast response!

**Comment by rfodge** [comment]
@tcamin I'm actually still seeing these errors within XCode even though we have that config.build_settings flag set.  
<img width="616" alt="Screen Shot 2022-01-27 at 2 32 14 PM" src="https://user-images.githubusercontent.com/11653643/151430512-a6ce2ef6-171c-473a-8987-9262ce0d1300.png">

<img width="632" alt="Screen Shot 2022-01-27 at 2 39 39 PM" src="https://user-images.githubusercontent.com/11653643/151431585-c6468171-de29-4157-8a72-f48fa9562298.png">

<img width="238" alt="Screen Shot 2022-01-27 at 2 34 38 PM" src="https://user-images.githubusercontent.com/11653643/151431652-c2dc0ce7-190c-470c-b929-25a537739391.png">

**Comment by tcamin** [comment]
Both those flags should be added to sbtuitestunnel’s targets, not the app target

**Comment by rfodge** [comment]
These....
![image (5)](https://user-images.githubusercontent.com/11653643/151433277-e599af5e-7924-46b0-8f9e-ce287d458861.png)

![image (4)](https://user-images.githubusercontent.com/11653643/151433301-095e6de1-30ed-4638-92e6-cda974279efc.png)

![image (3)](https://user-images.githubusercontent.com/11653643/151433324-e67ebd07-da12-419d-8355-d22e504b56eb.png)


Our PodFile has 
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'UI-TESTS' || config.name == 'UI-TESTS-LOCAL' || config.name == 'UI-TESTS-LOCAL-MONE'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1', 'ENABLE_UITUNNEL_SWIZZLING=1']
	        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "DEBUG"
            end
        end
    end
end

**Comment by rfodge** [comment]
<img width="759" alt="Screen Shot 2022-01-27 at 3 24 42 PM" src="https://user-images.githubusercontent.com/11653643/151438075-8690f629-b211-477c-b54a-494e30977a82.png">

**Comment by tcamin** [comment]
Could you show your Podfile in detail? From your previous post I see the following:

```
pod 'GCDWebServer', '~> 3.5.4'
pod 'SBTUITestTunnelClient', '~> 8.2.0'
pod 'SBTUITestTunnelCommon', '~> 8.2.0'
```

Which doesn't look right since the following should go in the UI Test Target

```
target 'UITestTarget' do
  pod 'SBTUITestTunnelClient', '~> 8.2.0'
  pod 'SBTUITestTunnelCommon', '~> 8.2.0'
end
```

while the app target should look like

```
target 'AppTarget' do
  pod 'GCDWebServer', '~> 3.5.4'
  pod 'SBTUITestTunnelServer', '~> 8.2.0'
  pod 'SBTUITestTunnelCommon', '~> 8.2.0'
end
```

**Comment by rfodge** [comment]
This resolved my issue, thanks so much for your help.

**Comment by rfodge** [comment]
This solved my issue, thank you for your help.  I do still see this occurring on my M1 mac but I think it is due to an issue related to us having multiple targets, one for intel and one for M1.  I do not see the compile errors occur on my intel, but I do on my m1 target but i'm still able to build and run my tests on my M1.  I need to investigate into it further to see if I can figure anymore information out so i'm going to close this.  Thanks again.
