### ISSUE TITLE
Module 'GCDWebServer' not found error when running App

### ISSUE THREAD

**Issue by maninderjeetsingh1** [Subito-it/SBTUITestTunnel#128]
I'm trying to integrate SBTUITestTunnel in my Objective C project which uses cocoapods for dependency management.

I have followed all the Installation & Setup guidelines mentioned in the Github [here](https://github.com/Subito-it/SBTUITestTunnel/tree/master/Documentation).

Added  following to My Apps Target
`pod 'SBTUITestTunnelServer'
  pod 'GCDWebServer', :inhibit_warnings => true
`
and, added below to my UITest target
`pod 'SBTUITestTunnelClient'`

Along with above I've also added below code to my AppDelegate file
`#import "SBTUITestTunnelServer.h"`
Added below in the method didFinishLaunchingWithOptions
`#if DEBUG
    [SBTUITestTunnelServer takeOff]
#endif`

And did `pod install`
I can see all the dependencies are getting downloaded but when I'm running my test target. I'm getting error 
/<Project_PATH>/ios-app/myios-app/Pods/SBTUITestTunnelServer/Sources/SBTUITestTunnelServer/SBTUITestTunnelServer.m:30:9: Module 'GCDWebServer' not found

Kindly help me on resolving this. 

<img width="1000" alt="Screenshot 2021-12-01 at 10 10 42 PM" src="https://user-images.githubusercontent.com/17909770/144276974-9c76de08-44e6-4ca9-8f10-9a0ee3f9dd26.png">

**Comment by tcamin** [comment]
Can you replicate the issue in a sample project you can share?

**Comment by maninderjeetsingh1** [comment]
Tried it. Could not replicate the issue in sample project. I did same setup for both the projects but its failing in my real project.

**Comment by ispiryan** [comment]
Same proble.

**Comment by isaac-weisberg** [comment]
Same problem - just out of the blue, randomly, Xcode suddenly decided that it's all gone.
