### ISSUE TITLE
Cannot build project using SBTUITestTunnel as SPM

### ISSUE THREAD

**Issue by shamanec** [Subito-it/SBTUITestTunnel#133]
1. Added SBTUITestTunnel as SPM according to the installation process.
2. Set up the preprocessor macro settings according to the setup process.
3. When I try to build the project I get the following error:  
The package product ‘SBTUITestTunnelServer’ cannot be used as a dependency of this target because it uses unsafe build flags.

**Comment by tcamin** [comment]
Did you add the master branch or did you pin to a tag? BTW Xcode 13 is required when using SPM (exactly because of this)

**Comment by shamanec** [comment]
I used the master branch, but I was trying to compile with Xcode 12.5 so probably this is the reason I encounter a failure.. Thanks for the heads up, I'll see if I can do it using Xcode 13 and close the issue!

**Comment by shamanec** [comment]
Managed to build successfully on Xcode 13, now off to try out this amazing project. Thank you again for the information!

**Comment by molind** [comment]
Hmm. I'm on master branch and using XCode 13. Same error. Any clues how to avoid it?

**Comment by molind** [comment]
Hmm again. Found this in Xcode 13 what's new: `Root packages and branch-based package dependencies can now use unsafeFlags in their target settings. (53679279)`.

**Comment by shamanec** [comment]
Did you add the SPM using the Xcode UI or with Package.swift file? Did you clean your DerivedData folder? To switch to Xcode 13 I completely removed my older Xcode versions and the whole ~/Library/Developer folder before I managed to get it working.

**Comment by molind** [comment]
Yeah, I've first added it by version. Seen this bug, added it by branch. It doesn't work. Then I cleaned everything including Derived Data and now app builds. SPM is quite difficult to use IMHO.

**Comment by shamanec** [comment]
Glad to hear you got it working!

**Comment by bartzet** [comment]
Hello.

When running the test that's using SBTUITestTunnel I'm getting the error:

```
error: The package product 'SBTUITestTunnelClient' cannot be used as a dependency of this target because it uses unsafe build flags. (in target 'UITests' from project 'XXX')
```

I'm using SPM and this version 👇
![image](https://user-images.githubusercontent.com/23279455/192715323-6550e107-0ba7-4915-92b1-a01e82517829.png)

I build the project with Xcode 13.3.1
I tried cleaning the derived data and build folders but that didn't help.
