### ISSUE TITLE
Stubbing not working on real devices

### ISSUE THREAD

**Issue by shamanec** [Subito-it/SBTUITestTunnel#134]
Hey, team! 

I've been using SBTUITestTunnel to run UI tests with stubbed responses on simulators successfully without issues. When I try running the same tests on real device the responses are not stubbed and instead they are just passed through to the live server. I see SBTUITestTunnel reporting that it connected and is ready and I don't see any errors related to it - the responses are just not stubbed. What could be a potential issue that could cause this and I could look into?

Thank you in advance,
Nikola

**Comment by tcamin** [comment]
Hi, I did a quick check on a sample project on a real device and everything works as expected. Are you sure stubs are set on time? Maybe the sequence of events on real device are different that those on simulators. On the other hand let me know if you manage to replicate the issue in a project that you can share and I'll take a look!

**Comment by shamanec** [comment]
All my issues are like practical jokes. I definitely have them when I open them and no longer have them when I get a reply... :D I did some changes for my simulator tests and maybe one of them fixed it because I can now successfully mock on real device. All in all amazing project, much better than our previous external mock-server. My only complaint is the timeouts when attaching the debugger but Xcode is a sad, sad tool :D Thanks for the reply!
