### ISSUE TITLE
Stubbing from the initial loading of the app occassionally fails

### ISSUE THREAD

**Issue by shamanec** [Subito-it/SBTUITestTunnel#135]
Hello, team!

I am trying to stub responses from the initial loading of the app for Homepage tests. It appears to me that sometimes the app loads before the tunnel establishes a connection and the responses are not stubbed which fails the tests. Is there any way you would recommend to handle this?

My setup:
1. Call app.launchTunnel().
2. Call a function that sets up the stubs immediately after.
3. Do validations

Thank you in advance,
Nikola

**Comment by tcamin** [comment]
You should add the stub in the launch block to be sure it is active once the app starts.

```
app.launchTunnel(withOptions: []) { 
   let match = ...
   let response = ...
   app.stubRequests(matching: match, response: response)
}
```

**Comment by shamanec** [comment]
I tried that but it does not seem to be the issue, responses are being mocked successfully on any local machine but they fail on our CI machine so it is probably some unknown problem on that side. Thank you for the response, closing this issue until I get more information why it happens!
