### ISSUE TITLE
`setUserInterfaceAnimationSpeed` freeze app on UI test start

### ISSUE THREAD

**Issue by piotrsmajek** [Subito-it/SBTUITestTunnel#139]
XCode 13.3.1 
MacOS 12.4 
MacBook Pro (M1, 2020)

When I'm using `setUserInterfaceAnimationSpeed(100)` from `SBTUITestTunnel` my app freeze on UI test start and when I delete this line and change for `window?.layer.speed = 2.0` for improve ui test speed everything is ok. 

Does anyone have the same problem?

**Comment by tcamin** [comment]
Hi, we set `setUserInterfaceAnimationSpeed(200)` in our codable and UI tests run correctly.

Are you able to replicate this behavior in a sample project that you could share?
