### ISSUE TITLE
Array JSON and stubRequests

### ISSUE THREAD

**Issue by YannickSteph** [Subito-it/SBTUITestTunnel#14]
Hi, thanks for your project.

I have in my project an array JSON, But how put this with stubRequests ?
Because is not a dictionary, and with returnJsonFileName can't load this format.
`
[
	{
		color: "red",
		value: "#f00"
	},
	{
		color: "green",
		value: "#0f0"
	},
	{
		color: "blue",
		value: "#00f"
	},
	{
		color: "cyan",
		value: "#0ff"
	},
	{
		color: "magenta",
		value: "#f0f"
	},
	{
		color: "yellow",
		value: "#ff0"
	},
	{
		color: "black",
		value: "#000"
	}
]
`

**Comment by tcamin** [comment]
That's becausee what you posted is not a valid json. From the [json standard introduction](https://tools.ietf.org/html/rfc7159):

> An object is an unordered collection of zero or more name/value
   pairs, where a name is a string and a value is a string, number,
   boolean, null, object, or array.

Your names are no strings, I'm guessing your data should be something like

`[ { "color": "red", "value": "#f00" }, { "color": "green", "value": "#0f0" }]...`

**Comment by YannickSteph** [comment]
Thanks for your answer, I realized after I had wrong post the format. It looks exactly like the format you put and I still have the same error the json file is not loading.

**Comment by YannickSteph** [comment]
My file json contains this structure, but is not return this value.. when i call fromJsonFile.
`
[
    {
        "test_1" : 2,
        "test_2" : "TEST",
        "test_3" : 36,
        "test_4" : null,
        "test_5" : 0,
        "test_6" : null,
        "test_7" : null,
        "test_8" : 117,
        "test_9" : null,
        "test_10" : "2016-08-16T22:48:51.000Z",
        "test_11" : 189,
        "test_12" : null,
        "test_13" :
        {
            "test_14" : 36,
            "test_15" : "Name",
            "test_16" : "Desc",
            "test_17" : "2012",
            "test_18" : "12",
            "test_19" : "https://test.JPG"
        },
        "test_20" : "TEST",
        "test_21" : 4,
        "test_22" : 0,
        "test_23" : 402499,
        "test_24" : "2016-08-17T21:58:15.000Z",
        "test_25" : 4,
        "test_26" : null,
        "test_27" : null,
        "test_28" : "2016-10-22T23:48:00.000Z"
    },
    {
        "test_1" : 2,
        "test_2" : "TEST",
        "test_3" : 36,
        "test_4" : null,
        "test_5" : 0,
        "test_6" : null,
        "test_7" : null,
        "test_8" : 117,
        "test_9" : null,
        "test_10" : "2016-08-16T22:48:51.000Z",
        "test_11" : 189,
        "test_12" : null,
        "test_13" :
        {
            "test_14" : 36,
            "test_15" : "Name",
            "test_16" : "Desc",
            "test_17" : "2012",
            "test_18" : "12",
            "test_19" : "https://test.JPG"
        },
        "test_20" : "TEST",
        "test_21" : 4,
        "test_22" : 0,
        "test_23" : 402499,
        "test_24" : "2016-08-17T21:58:15.000Z",
        "test_25" : 4,
        "test_26" : null,
        "test_27" : null,
        "test_28" : "2016-10-22T23:48:00.000Z"
    }
]
`

**Comment by tcamin** [comment]
What is it returning instead?

**Comment by YannickSteph** [comment]
Is return the data of API and not the file Json.

**Comment by YannickSteph** [comment]
Ok i found why.

When i execute request with url like that, not work : 
`http://apitest.fr/api/test?status=IN_PROGRESS%2CPREPARED`

 But when, it works
`http://apitest.fr/api/test`

**Comment by tcamin** [comment]
Then you're probably not setting the right SBTMatchingRequest
