### ISSUE TITLE
Very long time to execute `SBTUITestTunnelServer.takeOff()`

### ISSUE THREAD

**Issue by acecilia** [Subito-it/SBTUITestTunnel#144]
Hi 👋 

I am experiencing that executing `SBTUITestTunnelServer.takeOff()` takes very long time, between 20 to 60 seconds. I am using latest version `8.3.0`. This happens with `SBTUITestTunnelDisableIPC` `true` or `false`.

Is this expected?

Thanks

**Comment by ispiryan** [comment]
error build: The package product 'SBTUITestTunnelServer' cannot be used as a dependency of this target because it uses unsafe build flags.

**Comment by acecilia** [comment]
@tcamin Thanks for the quick response. I will try and let you know.

Do you know, how long is `takeOff` supposed to take?

**Comment by acecilia** [comment]
> I will try and let you know

I did unmark `Debug executable` from the Xcode scheme. I see that `takeOff` takes variable times of at least 10 seconds.

**Comment by tcamin** [comment]
> Do you know, how long is takeOff supposed to take?

Consider that `takeOff` completes once both runner app and app under tests are launched, so the time that is logged to console (_Tunnel ready after 3.760287s_) doesn't simply account to the library implementation. For our app on an M1 we see times in the range of 3-6s.

**Comment by acecilia** [comment]
> completes once both runner app and app under tests are launched

I do not fully understand. I am executing `takeOff` from inside the delegate, so the moment `takeOff` is invoked, I think both app and app runner are already launched. No?

I did not rely on the _Tunnel ready after 3.760287s_ text. The way I am measuring the delay is by doing this:
```
print("\(Date().timeIntervalSince1970) - before takeoff")
SBTUITestTunnelServer.takeOff()
print("\(Date().timeIntervalSince1970) - after takeoff")
```

I am also running on M1

**Comment by tcamin** [comment]
The `takeOff()` method is taking around 1s.

**Comment by tcamin** [comment]
> > completes once both runner app and app under tests are launched
> 
> I do not fully understand. I am executing `takeOff` from inside the delegate, so the moment `takeOff` is invoked, I think both app and app runner are already launched. No?

I didn't understand you were referring to the sole `takeOff` method but instead were mentioning the time logged on the runner app side (_Tunnel ready after ..._)

> 
> > so the time that is logged to console (Tunnel ready after 3.760287s) doesn't simply account to the library implementation
> 
> I did not rely on the _Tunnel ready after 3.760287s_ text. The way I am measuring the delay is by doing this:
> 
> ```
> print("\(Date().timeIntervalSince1970) - before takeoff")
> SBTUITestTunnelServer.takeOff()
> print("\(Date().timeIntervalSince1970) - after takeoff")
> ```
> 
> I am also running on M1
> 
> > For our app on an M1 we see times in the range of 3-6s.
> 
> Thanks for that info. I would say that is also a considerable amount of time. I think a reasonable amount of time for a big UITests is 30 seconds: 6 seconds delay is 20% of the total test execution time

The takeOff() method is taking around 1.5s.

**Comment by tcamin** [comment]
> > completes once both runner app and app under tests are launched
> 
> I do not fully understand. I am executing `takeOff` from inside the delegate, so the moment `takeOff` is invoked, I think both app and app runner are already launched. No?

I didn't understand you were referring to the sole `takeOff` method but instead were mentioning the time logged on the runner app side (_Tunnel ready after ..._)

> 
> > so the time that is logged to console (Tunnel ready after 3.760287s) doesn't simply account to the library implementation
> 
> I did not rely on the _Tunnel ready after 3.760287s_ text. The way I am measuring the delay is by doing this:
> 
> ```
> print("\(Date().timeIntervalSince1970) - before takeoff")
> SBTUITestTunnelServer.takeOff()
> print("\(Date().timeIntervalSince1970) - after takeoff")
> ```
> 
> I am also running on M1
> 
> > For our app on an M1 we see times in the range of 3-6s.
> 
> Thanks for that info. I would say that is also a considerable amount of time. I think a reasonable amount of time for a big UITests is 30 seconds: 6 seconds delay is 20% of the total test execution time

The takeOff() method is taking around 1.5s.

**Comment by acecilia** [comment]
I use the completion block to setup network mocks like follows:
```
app.launchTunnel {
    // Here I add network stubs
}
```

Maybe is the stubbing that takes time, not so much the takeOff itself?

**Comment by acecilia** [comment]
> Can you share the launch block that is causing the unusually long delay?

It is not one specific, I see it in many of the blocks in my tests. Sorry cant share, but can explain a bit more.

The stubs are in the order of 150, and are encoding `Encodable` structs into data that gets passed to the `stubRequests` method:

```
app.stubRequests(
    matching: SBTRequestMatch(url: "/myurl*", method: "GET"),
    response: SBTStubResponse(encodable: encodableStruct, returnCode: 200)
)
```

I already made sure that the `encoding` is not the part taking time (I removed the encoding code and passed `Data()` to `SBTStubResponse`)

**Comment by acecilia** [comment]
I could confirm that the amount of stubbing is the root cause of the failure. Explanation here: https://github.com/Subito-it/SBTUITestTunnel/pull/145

**Comment by acecilia** [comment]
I managed to troubleshoot this. The delay happens when having [zscaler](https://www.zscaler.com/) enabled. I think at this point it is not an issue of `SBTUITestTunnel`, but more a problem of zscaler. Thanks so much @tcamin for your help :raised_hands

**Comment by tcamin** [comment]
Does this happen both with and without using IPC?

**Comment by acecilia** [comment]
I am trying to check, but at the moment I cannot launch the app with IPC and am getting `Shutting down with error: '[SBTUITestTunnel] Failed getting IPC proxy, Error Domain=DTXIPCErrorDomain Code=1 "Connection <DTXIPCConnection: 0x600002922d60> is invalid." UserInfo={NSLocalizedDescription=Connection <DTXIPCConnection: 0x600002922d60> is invalid.}'`

**Comment by tcamin** [comment]
Are you testing on physical devices or simulators?

**Comment by acecilia** [comment]
Simulator :)
