### ISSUE TITLE
Re-establish connection without having to launch app again

### ISSUE THREAD

**Issue by dramos126** [Subito-it/SBTUITestTunnel#148]
Is there a way to re-establish SBTUITestTunnel connection without having to use `launchTunnel()`?
Tests are executed on BrowserStack and it seems the Test Runner loses connection after the test where he app was launched. If possible I'd like to avoid launching the app on every test.

**Comment by tcamin** [comment]
XCUITests kills the both the application and runner app after each tests. For this reason the tunnel needs to be reestablished on eanch test. I'm unfamiliar with BrowserStack but I'm unsure exactly which issue you are facing.

**Comment by dramos126** [comment]
@tcamin  thanks for a quick response!

When executing a Test Class that has 10 Test Cases - the app and runner are only killed at the end of the Test Class and not each individual test. In my `setUp()` I only call  `launchTunnel()` when the app is not running in the foreground. This works wells for me in my local environment. 

In the BrowserStack environment the app will remain open/active from test to test but the runner will not. I am not sure their environment is set up and can likely resolve my issue by calling  `launchTunnel()` in `setUp()` every test if executing in that environment - was just hoping there was a way to establish a connection from the test runner to the app without having to relaunch app on each test.

**Comment by tcamin** [comment]
Sounds like BrowserStack has a customized implementation of the tests execution which is not supported by our library.

**Comment by dramos126** [comment]
Thanks again @tcamin. Going to close this issue.
