### ISSUE TITLE
Tuist: Could not build Objective-C module 'SBTUITestTunnelCommon'

### ISSUE THREAD

**Issue by Ricardo-AWsoftware** [Subito-it/SBTUITestTunnel#155]
I follow all the steps to install and setup SBTUItunnel, I'm using **Tuist 3.15.0** to generate the Xcode Project but when I try to run the UITest I get the ` _Could not build Objective-C module **'SBTUITestTunnelCommon'**_ ` error

I added the `SBTUITestTunnelServer` target on my main target, also I added the `SBTUITestTunnelClient` target on my target of the UI Tests.

![image (1)](https://user-images.githubusercontent.com/103539654/211224604-edca665e-52ff-4be4-8f6f-e4f3243f9c97.png)

This is my configuration:
![SBTUITestTunnel](https://user-images.githubusercontent.com/103539654/211224258-f94462a9-9208-4000-b8ac-7130dc4afb7a.jpg)

The error is:
![image](https://user-images.githubusercontent.com/103539654/211224436-5f04bdee-99b2-42d2-846d-093b655b7986.png)

**Comment by kunimei** [comment]
good

**Comment by tcamin** [comment]
Could you provide a sample project that replicates this issue? From the screenshot the target list doens't look right since I wouldn't expect duplications there.
