### ISSUE TITLE
The app runs and hits the network before SBTUITestTunnel has chance to stub anything.

### ISSUE THREAD

**Issue by oliverfoggin** [Subito-it/SBTUITestTunnel#156]
I want to stub a network call that happens pretty much as soon as the app starts.

The first view in the app has an `onAppear` that calls a network end point.

In my test, this function runs before SBTUITestTunnel has chance to even stub the network endpoint so I can't test it.

**Comment by tcamin** [comment]
You should be able to stub the request adding the stub in the launchTunnel completionBlock which is synchronously invoked on tunnel takeOff.

**Comment by oliverfoggin** [comment]
I've got it set up that way...

I have this as the last thing in the didFinishLaunchingWithOptions...

```
#if DEBUG
SBTUITestTunnelServer.takeOff()
#endif

return true
```

And then in the tests...

```
override func setUp() {
	super.setUp()
	app.launchTunnel { [weak self] in
		self?.mockServerInvalidVersions()
	}
}

func mockServerInvalidVersions() {
	mockURLBuilder(url: "/versions", filepath: "invalid_version.json", method: "GET")
}

// MARK: URL Builder
private func mockURLBuilder(url: String, filepath: String, statusCode: Int = 200, method: String) {
	let base_url = "http://0.0.0.0:9292" // <- proxy server on my machine. This is the base URL.
	let path = url
	let complete_url = base_url + path
	let method = method
	let status_code = statusCode

	let requestMatch = SBTRequestMatch(url: complete_url, method: method)
	let response = SBTStubResponse(fileNamed: filepath, returnCode: status_code)
	app.stubRequests(matching: requestMatch, response: response)


	print("🍎🍎🍎🍎🍎🍎🍎 \(app.stubRequestsAll())")
}
```

And then the test looks like this...

```
func testInvalidVersions() {
	print("🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌")
	print(app.stubRequestsAll())
	print("🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌")

	updateAppScreen.trait.waitFor(.hittable)
}
```

The logs show...

```
🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
[URL: http://0.0.0.0:9292/versions
Query: N/A
Method: GET
Body: N/A
Request headers: N/A
Response headers: N/A: <SBTStubResponse: 0x600003ee7c80>]
🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌
```

So the stub is definitely there.

But the app starts up and hits my mock server and the app launches without using the stub.

Hmm...

**Comment by oliverfoggin** [comment]
Oh... It just worked... but only when the app went into maintenance mode because the back end is offline. But then when I hit "Try again" in the app (so after a few seconds) the app retried the launch again and hit the endpoint but this time went through the stub and so tested successfully.

So it looks like there's a delay that happens between launching the app and the stub actually being active.

**Comment by oliverfoggin** [comment]
I updated the setup to bring it all inline...

```
override func setUp() {
	super.setUp()

	app.launchTunnel { [weak self] in
		let base_url = "http://0.0.0.0:9292"
		let path = "/versions"
		let complete_url = base_url + path
		let method = "GET"
		let status_code = 200

		let requestMatch = SBTRequestMatch(url: complete_url, method: method)
		let response = SBTStubResponse(fileNamed: "invalid_version.json", returnCode: status_code)

		print(self?.app) // <---- THIS PRINT

		self?.app.stubRequests(matching: requestMatch, response: response)
	}
}
```

When the app prints out in this block it already shows the "Try again" button and "Maintenance mode" so the app has fully launched and has already hit the endpoint I want to test by this point.

**Comment by oliverfoggin** [comment]
OK I've moved this around a bit. After reading the setup guide again I moved the `takeOff()` line to the first line of the `didFinishLaunchingWithOptions`.

However... now, the rest of that whole function just doesn't run. It now appears to skip this entirely and goes on to the body of the initial view of the app.

But... in this view I use an implicitly unwrapped optional from the appDelegate. Which now isn't instantiated because the `didFinishLaunching` didn't run. So the app crashes.

**Comment by oliverfoggin** [comment]
Ah, ok, so I think I found the issue...

We're writing a SwiftUI app and have added an AppDelegate using this method... https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-an-appdelegate-to-a-swiftui-app

Which seems to change the order in which things are done. So the documentation here... https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md

That says...

> StartupBlock
> The startup block contains code that will be executed before the app enters the applicationDidFinishLaunching(_:). This is the right place to setup the application before it gets launched

Is not correct. In our app the AppDelegate runs BEFORE the startup block runs.

**Comment by oliverfoggin** [comment]
Here's the stack trace. As you can see the `takeOff` function eventually asynchronously calls the body getter of the app and so bypasses the rest of the `didFinishLaunching` function. And runs the app before the test can stub the calls.


![image](https://user-images.githubusercontent.com/1813244/214161183-b1749100-439f-47ae-a75c-bbeb80a07b8c.png)

**Comment by oliverfoggin** [comment]
I think I might have to update the startup of the app to be a old school UIKit type startup. And then use that to create the SwiftUI app.

😬

**Comment by tcamin** [comment]
I'll close this one since you opened another the other related issue #157

**Comment by oliverfoggin** [comment]
@tcamin that's cool. It would be good to get some input on this though? I gave up after a couple days of trying and I'm using Swifter now to act as a server for the app in UI Tests.

It looks like there is a fatal flaw in the SBTUITestTunnel in that if an app makes a request on launch then this framework just can't stub it in time. It gets there eventually but the app has launched already by the time that happens.

**Comment by tcamin** [comment]
The library supports setting stubs before the app launch. We use this
pattern extensively so I guess the problem lies with the SwiftUI
application that might not be yet supported.
