### ISSUE TITLE
SBTUITestTunnel and XCTest launchArguments/launchEnvironments

### ISSUE THREAD

**Issue by alexnot95** [Subito-it/SBTUITestTunnel#158]
Hi, I'm trying to use this library in our existing UI tests framework, we have a lot launchArguments/launchEnvironments which we are setting before XCUIApplication() launch, but as I see when I'm setting launchArguments/launchEnvironments for XCUIApplication() and then using app.launchTunnel() those arguments/environments are not exist... How can I use launchArguments/launchEnvironments with this library? Thanks

**Comment by tcamin** [comment]
Can you share a snippet of code of how you're setting the launchArguments/launchEnvironments and then launch the tunnel?

**Comment by alexnot95** [comment]
@tcamin sure, here is the code example:
```
import Foundation
import SBTUITestTunnelClient

class MockUITests: BaseTest {
    
    func testCheckAppArgumentsAndEnvironment() {
        launchApp(mockTurnedOn: true)
        print("App launchArguments: \(app.launchArguments)")
        print("App launchEnvieornments: \(app.launchEnvironment)")
    }
}
```

```
import SBTUITestTunnelClient
import XCTest

class BaseTest: XCTestCase {
   let testApplication = XCUIApplication()
        
    override func setUp() {
        super.setUp()
        continueAfterFailure = false
    }
    
    override func tearDown() {
        testApplication.terminate()
        super.tearDown()
    }
    
    func launchApp(appRegion: AppRegion = .EN,
                   appLanguage: AppLanguage = .en,
                   mockTurnedOn: Bool = false) {
        launchArgumentHandler.setLaunchArguments(region: appRegion, language: appLanguage)
        if mockTurnedOn {
            app.launchTunnel()
        } else {
            testApplication.launch()
        }
    }
}
```

```
import XCTest

let launchArgumentHandler = LaunchArgumentHandler()

class LaunchArgumentHandler {
    let globalArguments = ["animationOff", "hideWorkoutScreen", "-AppleLocale", "-AppleLanguages"]

    func setLaunchArguments(region: AppRegion, language: AppLanguage) {
        globalArguments.forEach {
            if $0 == "-AppleLocale" {
                testApplication.launchArguments += [$0, "\"\(region.rawValue)\""]
            } else if $0 == "-AppleLanguages" {
                testApplication.launchArguments += [$0, "(\(language.rawValue))"]
            } else {
                testApplication.launchArguments += [$0]
            }
        }
    }
}
```

When I'm running above test I see in console:
```
App launchArguments: ["SBTUITunneledApplicationLaunchSignal"]
App launchEnvieornments: ["SBTUITunneledApplicationLaunchEnvironmentIPCKey": "EFC4A6CC-F08F-4561-89A8-3F602559CBBC"]
```
but If print launchArguments for XCUIApplication() I see my arguments which I set, maybe I'm doing something wrong and I need set this arguments additionaly to SBTApplication somehow?

**Comment by tcamin** [comment]
I believe you're setting the  launchArguments to the `testApplication` instance which is unrelated to the `app` instance exposed by the SBTUITestTunnel. You should set the launchArguments of the `app` instance instead, since that is the proxy that will launch the application under test

**Comment by alexnot95** [comment]
@tcamin So this code should work for setting launchArguments and Environment?
```
app.launchArguments += ["animation"]
app.launchEnvironment += ["key": "value"]
```

And I need import SBTUITestTunnelClient to work with app instance right?

**Comment by tcamin** [comment]
Yes. Using the `app` instance is the recommended way because it's the most straight forward way to use it. You can however rely on different instances of XCUIApplication following [the docs](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Setup_alternative_target.md) but that is generally unnecessarily complicated.

**Comment by alexnot95** [comment]
Hi @tcamin I have some questions, cuz I don't understand why I can't stub any network request:
1. I see errors when try to use code from examples of usage 
<img width="1283" alt="Screenshot 2023-01-30 at 20 58 53" src="https://user-images.githubusercontent.com/37154209/215582361-6937eb9a-bea2-4838-b2cf-657321fda551.png">
2. Also why I see erros when trying to use app in my code? 
<img width="1295" alt="Screenshot 2023-01-30 at 20 59 38" src="https://user-images.githubusercontent.com/37154209/215582511-b29adc6a-f17e-42de-b135-ebc39a84b106.png">

Maybe i'm doing something wrong? Library connected via SPM, if I'm running code without my attempt to stub something everything works fine

**Comment by tcamin** [comment]
The package might not have been installed correctly. Server package should go in the app target and client one in uitest target.

Wrt to 1. you should not set stubs before launching the tunnel, instead use the launch block to set any required stub before the app starts.

Refer to the sample project tests
