### ISSUE TITLE
Receiving GCDWebServer font error when trying to upload build to AppStore

### ISSUE THREAD

**Issue by alexnot95** [Subito-it/SBTUITestTunnel#165]
Hi, I've recently integrated SBTUITestTunnel lib in the project via SPM, everything works good, but when I tried to upload build to AppStore, I received decline from Apple cuz of this error: 
```
ITMS-90853: Invalid font - There was an error validating the font at 'XXX.app/GCDWebServer_GCDWebServer.bundle/GCDWebUploader.bundle/Contents/Resources/fonts/glyphicons-halflings-regular.woff'. Font not supported by platform.
```

Build made with XCode 14.2

Maybe there is any workaround to use this lib with GCDWebServer dependency without this error? Thanks

**Comment by alexnot95** [comment]
Hi @tcamin I found how to fix this issue, as I see you have GCDWebServer as a dependency and you forked it? Maybe you can make these changes and everything will work without error from Apple? 

https://github.com/d-i-t-a/GCDWebServer/pull/1/files

**Comment by tcamin** [comment]
You should never ship your app with testing code. A much safer approach is to create a separate target for your AppStore submission that doesn't include SBTUITestTunnel and GCDWebServer instead.
