### ISSUE TITLE
Manual install library question

### ISSUE THREAD

**Issue by alexnot95** [Subito-it/SBTUITestTunnel#167]
Hi @tcamin , If I want to integrate library manually, I can't understand some points:
<img width="1087" alt="Screenshot 2023-02-10 at 13 49 44" src="https://user-images.githubusercontent.com/37154209/218096533-19659933-4d00-4c5e-8ab0-e7cc7fb012bf.png">

1,2,3 - I need to make a Frameworks from Client/Common/Server? And later in step 6 add this Frameworks in appropriate targets in Link Binaries?

4 - GCDWebServer should be in this location? app.xcodeproj/GCDWebServer ?
5 - Add header search path in build settings for GCDWebServer should be added only for main app target and not in ui tests target?
6 - I need to link it in main and UI tests targets? Like Server to main and Common + Client to UI tests? And it should be Frameworks?

Thanks

**Comment by tcamin** [comment]
The manual installation steps date back to when most project were mixed Objective-C/Swift and I should consider removing this from docs to avoid any confusion. I think it should be better to sort out the issues you're having with SPM or CocoaPods instead.

**Comment by alexnot95** [comment]
Thanks for the explanation
