### ISSUE TITLE
SBTUITestTunnelClientDelegate conflicts with fastlane

### ISSUE THREAD

**Issue by magauran** [Subito-it/SBTUITestTunnel#169]
I use `SBTUITestTunnelClientDelegate` in my tests and implement two methods:

- `testTunnelClientIsReadyToLaunch:`
- `testTunnelClient:didShutdownWithError`

Both of these methods have the "test" prefix.

Also, to run tests on CI, I use `multi_scan` from fastlane, that looks for methods named `test*`.
As a result, faslane thinks that the delegate methods are tests, tries to run them and crashes.

Can we rename these two methods? I can open a pull request with this.

**Comment by tcamin** [comment]
Took longer than expected but the rename just got merged.
