### ISSUE TITLE
Unclear how to use the library to monitor requests on multiple hosts

### ISSUE THREAD

**Issue by kirhgoff** [Subito-it/SBTUITestTunnel#173]
Hello,

This is not a problem, but more a request for an explanation. I wanted to add some checks to test multiple tracking systems used in the app - Firebase, Branch, homemade one, etc.

I created a class that does that (shortened version)
```
    typealias InterceptedRequest = SBTMonitoredNetworkRequest
    typealias RequestPredicate = (InterceptedRequest) -> Bool

    let WAIT_FOR_REQUEST_TIMEOUT = 2

    let app: SBTUITunneledApplication
    var requests = [InterceptedRequest]()

    init(_ app: SBTUITunneledApplication, urlPattern: String) {
        self.app = app
        XCTAssertNotNil(app.monitorRequests(
            matching: SBTRequestMatch.init(url: urlPattern)
        ))
    }

    func findRequest(_ predicate: RequestPredicate, errorMessage: String) -> InterceptedRequest {
        let startTime = Date()

        while !requests.contains(where: predicate) && Date().timeIntervalSince(startTime) < 2.0 {
            requests.append(contentsOf: app.monitoredRequestsFlushAll())
            usleep(10000) // sleep for 10 ms not to block
        }

        let index = requests.lastIndex(where: predicate)

        guard let index else {
            fail(errorMessage)
        }

        return requests.remove(at: index)
    }
```

I was going to derive this class providing multiple url patterns for each tracking system and test if I can find appropriate request for each system. 

But then I noticed that `monitoredRequestsFlushAll` is a method on the app that cannot detect which pattern is being monitored. So I am guessing the monitoring is global and one instance of my checker would be stealing the requests from another checker. 

I saw some people monitor requests with `.*` pattern. Should I do the same and have one instance that monitors all the URLs and then find requests to the hosts I am interested in?

**Comment by tcamin** [comment]
Instead of using `monitoredRequestsFlushAll` you can use `monitoredRequestsPeekAll` which will not clear the list of network requests.

Wrt to the pattern to use it really depends on the context. Instead of adding all requests with `.*` you could add all the requests that are needed, for examples

```
let firebaseMatch = SBTRequestMatch(url: "firebase.com")
let appleMatch = SBTRequestMatch(url: "apple.com")

for match in [appleMatch, firebaseMatch] {
    app.monitorRequests(matching: match)
}

// Navigate app

XCTAssert(app.waitForMonitoredRequests(matching: appleMatch, timeout: 5.0)) // wait for at least one apple request
let allAppleRequests = app.monitoredRequestsPeekAll().filter { $0.matches(appleMatch) }

// Do something else

XCTAssert(app.waitForMonitoredRequests(matching: firebaseMatch, timeout: 5.0, iterations: 3)) // wait for at least 3 firebase requests
let allFirebaseRequests = app.monitoredRequestsPeekAll().filter { $0.matches(firebaseMatch) }

app.monitoredRequestsFlushAll() // clear all collected requests
```

Hope this helps!
