### ISSUE TITLE
Can't install 9.0.0

### ISSUE THREAD

**Issue by ahmedsalah196** [Subito-it/SBTUITestTunnel#175]
Hello!
I can see that the latest version in the .podspec file is `9.0.0` but the latest release tag is `8.3.0`. So, cocoapods always fallbacks to `8.3.0`. I'm looking forward to install [this fix](https://github.com/Subito-it/SBTUITestTunnel/pull/140) which was merged a long time ago. Any idea what I need to do?

Thanks!

**Comment by tcamin** [comment]
The 9.0.0 has not been published yet, for the time being you can update your Podfile to point to the master branch

```
    pod 'SBTUITestTunnelClient', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git', :branch => 'master'
    pod 'SBTUITestTunnelCommon', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git', :branch => 'master'
    pod 'SBTUITestTunnelServer', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git', :branch => 'master'
```

or to a specific commit
```
    pod 'SBTUITestTunnelClient', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git', :commit => '683ad7f'
    pod 'SBTUITestTunnelCommon', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git', :commit => '683ad7f'
    pod 'SBTUITestTunnelServer', :git => 'https://github.com/Subito-it/SBTUITestTunnel.git', :commit => '683ad7f'
```

**Comment by yousefhamza** [comment]
@tcamin when do you expect to release 9.0.0?

**Comment by tcamin** [comment]
Within the next few weeks

**Comment by Skeptick** [comment]
@tcamin
Hello! We ran into a problem that when dependency on `SBTUITestTunnelCommon` was not explicitly specified in Podfile. CI was pulling version 9.0.0 (while `SBTUITestTunnelClient` and `SBTUITestTunnelServer` were 8.3.0), which caused fastlane to fail to upload build to TestFlight with error

> Non-public API usage - The app references non-public symbols in AppName: ___NSMakeSpecialForwardingCaptureBlock.

I don’t know why it happened, the problem was fixed by explicitly specifying `SBTUITestTunnelCommon` to 8.3.0.
JFYI.
It would be cool if you could explain why 😊

**Comment by tcamin** [comment]
@Skeptick: this is expected due to some swift defines/c preprocessor macros being removed. You should update your project and make sure it doesn't include the testing dependency when submitting the app to TestFlight/AppStore.
