### ISSUE TITLE
Cannot start UI Test

### ISSUE THREAD

**Issue by jaynakus** [Subito-it/SBTUITestTunnel#18]
I can see that application registers stubs and probably gets initialized. However, UI test module says it cannot connect... What could be the problem?

`2016-12-27 09:17:04.915 [41163:320762] Multiple stubs registered for request <NSURLRequest: 0x60800000d210> { URL: https://app-measurement.com/a }!
2016-12-27 09:17:04.915[41163:320762] -> {
    SBTProxyURLProtocolBlockKey = "<__NSMallocBlock__: 0x608001467240>";
    SBTProxyURLProtocolMatchingRuleKey = "URL: N/A\nQuery: .*get_user_info.*\nMethod: N/A";
    SBTProxyURLProtocolStubResponse = "data-length: 318\nstatusCode: 200\nresponseTime: -1500.00\nheaders: {\n    \"Content-Length\" = 318;\n    \"Content-Type\" = \"application/json\";\n}";
}
2016-12-27 09:17:04.916[41163:320762] -> {
    SBTProxyURLProtocolBlockKey = "<__NSMallocBlock__: 0x60800146e080>";
    SBTProxyURLProtocolMatchingRuleKey = "URL: N/A\nQuery: .*store.*\nMethod: N/A";
    SBTProxyURLProtocolStubResponse = "data-length: 26\nstatusCode: 200\nresponseTime: -1500.00\nheaders: {\n    \"Content-Length\" = 26;\n    \"Content-Type\" = \"application/json\";\n}";
}`

`failed: caught "NSInternalInconsistencyException", "[SBTUITestTunnel] failed waiting app to be ready"
(
	0   CoreFoundation                      0x000000010ce66d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c8c821e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ce6ae42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010c45d66d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   SBTUITestTunnel                     0x000000011e798134 -[SBTUITunneledApplication waitForServerReady] + 356
	5   SBTUITestTunnel                     0x000000011e797928 -[SBTUITunneledApplication launchTunnelWithOptions:startupBlock:] + 1240`

**Comment by tcamin** [comment]
Did you call takeoff of the application target?

**Comment by jaynakus** [comment]
Yes, I call it like this in AppDelegate
SBTUITestTunnelServer.takeOff()

**Comment by tcamin** [comment]
Does the sample project work?
Is this on a physical device or simulator?
Are you using `SBTUITestTunnelServer.takeOffCompleted(false)`?

**Comment by jaynakus** [comment]
I removed SBTUITestTunnelServer.takeOffCompleted(false) 
and now it seems to connect to server. Says:
2016-12-28 16:24:59.522 XCTRunner[76134:1664743] [UITestTunnel] Server detected!

But now I have another question. Is matching query with regex like this correct? 
`self.app.stubRequests(matching: SBTRequestMatch.query(".*get_user_info.*"),
                        return: self.stubs[a]!.data(using: .utf8)!,
                        contentType: "application/json",
                        returnCode: 200,
                        responseTime: SBTUITunnelStubsDownloadSpeedWifi)`

**Comment by jaynakus** [comment]
Or is there a logging that hints me if stub activated?

**Comment by tcamin** [comment]
If `get_user_info` is part of the URL as I suspect you should replace it with

`self.app.stubRequests(matching: SBTRequestMatch.url("get_user_info"), return: self.stubs[a]!.data(using: .utf8)!, contentType: "application/json", returnCode: 200, responseTime: SBTUITunnelStubsDownloadSpeedWifi)`

Take a look at the UI Tests in the Example project, it has a lot of typical usage examples
