### ISSUE TITLE
Swift UI and Swift Concurrency Support

### ISSUE THREAD

**Issue by rfodge** [Subito-it/SBTUITestTunnel#181]
Does the latest version of the tunnel (9.0) support apps created using Swift UI and/or Swift Concurrency (using multiple threads by using async/await)?   

I've been seeing some random crashes happening recently on a screen where we now use async / await / tasks so i was wondering if this functionality is supported by the latest version of the tunnel?  

Thanks

**Comment by tcamin** [comment]
The library is tested against code that uses async/await and for SwiftUI I did some fixes in the past. If you have a specific case where it doesn’t work please provide a sample project that reproduces the issue and I’ll try to take a look.

**Comment by rfodge** [comment]
Will you be adding a Scroll function for SwiftUI List view?

**Comment by lechuckcaptain** [comment]
@rfodge do you have a specific use case or sample app that is not working properly to share?

**Comment by rfodge** [comment]
@lechuckcaptain I do not.  I was just looking at the current functions that exist for scrolling within the tunnel and noticed that they are all for UIKit views so wasn't sure if you would be creating different ones for SwiftUI views like lists.  We are move to SwiftUI in the future so i was just preparing. 

<img width="488" alt="Screenshot 2023-08-03 at 10 22 10 AM" src="https://github.com/Subito-it/SBTUITestTunnel/assets/11653643/34779942-357d-4620-98e1-de22a4411239">

**Comment by tcamin** [comment]
Did you query the UITableView before scrolling? For example `XCTAssert(app.tables["vstack"].cells.count > 0)`?

**Comment by rfodge** [comment]
I did not but scrolling does work after i just added that!!! 😮     Why is that needed? 🤔
