### ISSUE TITLE
Rewrite Stubbed Responses

### ISSUE THREAD

**Issue by mfernandez94** [Subito-it/SBTUITestTunnel#183]
Was looking at the example project and the rewrite section, but can't seem to figure out how to use rewrite with stubbed responses from a local JSON file. Is that currently possible?

**Comment by tcamin** [comment]
The rewrite feature works on actual, non stubbed, network requests. I've updated the documentation accordingly. Given that you have the JSON file you could load it in a dictionary that would be modified dynamically as needed (instead of using rewrites).

**Comment by mfernandez94** [comment]
ah ok! thanks you!
