### ISSUE TITLE
Xcode 15.0 support

### ISSUE THREAD

**Issue by jszumski** [Subito-it/SBTUITestTunnel#186]
There are a few compiler and runtime warnings that show up in Xcode 15

- Deployment target of 11 is too low
- Compiler warnings for type mismatches and newer C behavior
- The non-`NSSecureCoding` use of archivers is deprecated in iOS 12+
- CFNetwork says an upload task shouldn't contain a body:
    > [CFNetwork] The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
- NSURLProtocol says `setProperty:forKey:inRequest:` should only be given property list types:
    > API MISUSE: <NSMutableURLRequest: 0x600000020b50> { URL: http://google.com/ } properties set by +[NSURLProtocol setProperty:forKey:inRequest:] should only include property list types (NSArray, NSDictionary, NSString, NSData, NSDate, NSNumber).
- NSURLProtocol completion handler not called:
    > API MISUSE: NSURLSession delegate SBTProxyURLProtocol: <SBTProxyURLProtocol: 0x60000263f840> (0x60000263f840)
    > API MISUSE: dataTask:didReceiveResponse:completionHandler: completion handler not called

I plan to put up a few PRs to address these.

**Comment by kirhgoff** [comment]
🙏🏼 Thank you very much!

**Comment by johnmalatras** [comment]
Doesn't look like this was intending to fix any breaking changes but FYI that I'm running into something: https://github.com/Subito-it/SBTUITestTunnel/issues/190

**Comment by tcamin** [comment]
Thanks for all the fixes!
