### ISSUE TITLE
define custom DEBUG pre-processor macro

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#19]
is there a way to use a custom DEBUG pre-processor macro without having to modify the pod files i.e use `#if DEBUG_CONFIG` instead for `#if DEBUG`, in my current project we are using custom DEBUG pre-processor.

**Comment by tcamin** [comment]
This is something I wanted to add some time ago end with version 1.3.2 I just release should be finally sorted out. Besides `DEBUG=1` we'll check also for `ENABLE_UITUNNEL=1`. **Make sure that the preprocessor macro is defined in your Pods as well!**. Check out the new documentation which has a dedicated paragraph.
