### ISSUE TITLE
Intermittent timeouts on iOS17/Xcode 15

### ISSUE THREAD

**Issue by johnmalatras** [Subito-it/SBTUITestTunnel#190]
Hi,

I've recently updated my CI (GitHub Actions) to use Xcode 15 / iOS17 / Swift 5.8 and I'm now getting timeouts in the majority of my UI tests without any consistency. Here's the error being thrown for each test:
`[SBTUITestTunnel] Waiting for startup block completion timed out (NSInternalInconsistencyException)`

Unfortunately there are no other error logs, and the build and my other unit tests succeed without issue. I'm on latest master of SBTUITestTunnel - is there anything else I might be missing?

**Comment by tcamin** [comment]
Can you replicate the issue locally? If not it is likely that your hitting
the same issue discussed  here:
https://discuss.circleci.com/t/severe-performance-problems-with-xcode-15/49205/35


Hi,

**Comment by johnmalatras** [comment]
No I'm not able to replicate locally. It appears that some of the runs fail before the tests are attempted with:
`The test runner failed to initialize for UI testing. (Underlying Error: Timed out while loading Accessibility.))`

Interesting! I'm not using CircleCI but definitely could be a similar issue. Looks like I might need to disable UI tests until Sonoma support is added: https://github.com/github/roadmap/issues/813
