### ISSUE TITLE
SBTUITestTunnel stops building

### ISSUE THREAD

**Issue by bartosz-pawelczyk** [Subito-it/SBTUITestTunnel#194]
Hi,
After upgrade to the newest commit [e0f131f](https://github.com/Subito-it/SBTUITestTunnel/commit/e0f131f5bd2ad98f5ab646caa966b24731cd1761) of library its not building.

<img width="1437" alt="Screenshot 2023-10-13 at 09 14 54" src="https://github.com/Subito-it/SBTUITestTunnel/assets/90895410/a2e4a1cd-2b2e-4bdd-958b-ce04a746011a">

**Comment by tcamin** [comment]
Hi, sorry for the inconvenience and thanks for the report! I've opened a [PR](https://github.com/Subito-it/SBTUITestTunnel/pull/195), will wait for tests and merge.

**Comment by tcamin** [comment]
Merged, can you check now?

**Comment by bartosz-pawelczyk** [comment]
@tcamin Build succeesed. Thanks for quick response and fix
