### ISSUE TITLE
Can't submit to App Store Connect: Invalid font GCDWebUploader.bundle/fonts/glyphicons-halflings-regular.woff

### ISSUE THREAD

**Issue by johnmalatras** [Subito-it/SBTUITestTunnel#200]
It appears that there is an odd issue myself and other folks are facing with the GCDWebUploader package (which SBTUITestTunnel depends on) after adding a widget target to your project. When uploading a build to App Store Connect, I get the error:

> ITMS-90853: Invalid font - There was an error validating the font at 'Substack.app/GCDWebServer_GCDWebServer.bundle/GCDWebUploader.bundle/Contents/Resources/fonts/glyphicons-halflings-regular.woff'. Font not supported by platform.

More cases of this can be found in [this](https://github.com/readium/swift-toolkit/issues/189) issue. As GCDWebUploader is deprecated and we are using a Subito-it fork (which you also can't raise an issue on), I'm hoping this could be resolved here. Could this font be removed from the fork? Otherwise any other ideas for solutions?

**Comment by tcamin** [comment]
While the issue could be addressed modifying the GCDWebServer fork I would strongly recommend you to ensure not including SBTUITestTunnel in your AppStore builds as detailed in the setup documentation [here](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Setup.md#-important-please-read)

**Comment by johnmalatras** [comment]
I'm wrapping all imports/usages in `#if DEBUG` but it appears to be building GCDWebServer anyways

**Comment by tcamin** [comment]
I would suggest to have a dedicated target that does not include the sbtuitesttunnel and other debug libraries at all. The problem is that although wrapping with if DEBUG guarantees the code is not executed it does prevent the code from being compiled (and copied into the final binary).

**Comment by johnmalatras** [comment]
Interesting, so is the suggestion to have two targets for the main application? One which is linked to sbtuitesttunnel and one which is and is used for tests?

**Comment by tcamin** [comment]
Yes, this guarantees that no testing code ends up in production with the
additional benefit of reducing the size of the app bundle.

**Comment by johnmalatras** [comment]
But in this case if you try to build the production target which has the sbtuitesttunnel dependency removed locally, it cannot find sbtuitesttunnel in AppDelegate. I suppose this new target without sbtuitesttunnel will need to strictly be used for production CD and not locally.
<img width="625" alt="Screenshot 2023-12-10 at 11 42 45 AM" src="https://github.com/Subito-it/SBTUITestTunnel/assets/11020161/d74a7060-ee55-483d-b609-619eeea10c76">

As the root cause here is a bug in the upstream library, could the invalid font be removed in the meantime? As it stands anyone with a widget cannot submit to Apple and we'll need to refactor some of our CI/CD process to support this new target.

**Comment by tcamin** [comment]
Would using `#if canImport(SBTUITestTunnelServer)` work instead?

**Comment by johnmalatras** [comment]
Yep that works! Awesome, I'll create a new target that I only have to use for UI tests which includes SBTUITestTunnelServer. Thanks for the help!
