### ISSUE TITLE
The package product 'SBTUITestTunnelClient/SBTUITestTunnelServer' cannot be used as a dependency of this target because it uses unsafe build flags.

### ISSUE THREAD

**Issue by ponienchen** [Subito-it/SBTUITestTunnel#201]
Hi, please lend me a hand.

My setups:

-  xcode 14.3.1
- using SBTUITestTunnel version 10.0.0
- I installed the library via swift package manager
- I added SBTUITestTunnelClient to the TestApp, and SBTUITestTunnelServer to the App
- I am using `let thirdPartyApp = SBTUITunneledApplication(bundleIdentifier: "xxx.yyy.zzz")` as the app under test, and I wrote the xcuitests test cases myself.
- When building the project, I got the error saying that `The package product 'SBTUITestTunnelClient/SBTUITestTunnelServer' cannot be used as a dependency of this target because it uses unsafe build flags.`

I think this error is caused by [this line](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Package.swift#L62) ...!? 

Could you please help me out with this issue ?

**Comment by tcamin** [comment]
Did you clone on the master branch as specified in the [installation docs ](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Installation.md#installation-swift-package-manager)?

**Comment by ponienchen** [comment]
You are absolutely right that I didn't set branch - master as the dependency rule.
Thank you!
