### ISSUE TITLE
Stubbing example looks like half swift and half objective C

### ISSUE THREAD

**Issue by kaomte** [Subito-it/SBTUITestTunnel#21]
This line would not compile. It is at least missing a parenthesis. 

`let stubId = app.stubRequestsMatching:SBTRequestMatch(SBTRequestMatch.URL("google.com"), returnJsonDictionary: ["key": "value"], returnCode: 200, responseTime: SBTUITunnelStubsDownloadSpeed3G)
`

**Comment by tcamin** [comment]
Fixed.
