### ISSUE TITLE
Timeout errors when running UI Tests in Xcode Cloud

### ISSUE THREAD

**Issue by bijancronin** [Subito-it/SBTUITestTunnel#214]
Not sure if it's Xcode Cloud or the test tunnel but all my UI tests are failing because of a timeout error on startup:

SBTUITestTunnel] Waiting for startup block completion timed out (NSInternalInconsistencyException)
SBTUITunneledApplication.m:57

**Comment by tcamin** [comment]
Hi! Never tried the library on XcodeCloud. Did you try [disabling IPC](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Setup.md#tunneling-mode)?

**Comment by tcamin** [comment]
Closing due to no response.
