### ISSUE TITLE
SBT-Client Linking Error - Physical Device Only

### ISSUE THREAD

**Issue by JustinM1** [Subito-it/SBTUITestTunnel#25]
I'm able to run on the simulator with no problem, but when I try to run on physical device I get:

Apple Mach-O Linker (id) Error

Unfortunately I can't share the project but was hoping you may have an idea of the cause based on it working on simulator but not on physical device.

**Comment by JustinM1** [comment]
after going through the logs I was able to determine it was a bitcode issue. Setting Enable Bitcode to No for Pods Project/ SBTUITestTunnel-Client Target fixed the issue.

**Comment by heikkihautala** [comment]
Add this to your podfile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'SBTUITestTunnel-Client'
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
end
```
