### ISSUE TITLE
Scrolling does not work

### ISSUE THREAD

**Issue by WesleyJacobsMP** [Subito-it/SBTUITestTunnel#28]
During the UI tests, my view does not scroll to the correct line automatically.
Before adapting SBTUITestTunnel, it did do this.
Is there some setting I am missing?

**Comment by tcamin** [comment]
Without further information, it is difficult to tell what's going on. Can you share a simple project showing the described behavior?

Wild guessing you may not be initializing things properly, for ex. you may be missing the takeOff() part in the AppDelegate. Check the README or the sample  project for more help

**Comment by WesleyJacobsMP** [comment]
I have found a solution in the meantime, by using the accessibilityIdentifier of the cell, the tests work as intended. Thanks for the quick response
