### ISSUE TITLE
View mock request via charles proxy

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#30]
It would be really useful to view actual mock network request via Charles proxy currently it displays the example below, which is not very useful for debugging

```
http://localhost:8666/commandStubPathMatching
```

```
{
	"result": "stb-e3a8eb03ca99a84f37ffb5a4436c098d39e78609"
}
```

**Comment by tcamin** [comment]
I have to check, but I'd said it's doable.

Gonna check asap.

**Comment by tcamin** [comment]
Done in 7f7d6d242519a727389010cb55e5cb19f30aee67
