### ISSUE TITLE
Set up requests before launchTunnel

### ISSUE THREAD

**Issue by Lukemufc91** [Subito-it/SBTUITestTunnel#32]
Is it possible to set up the mock requests before the app has launched? 
I am currently setting SBTUITestTunnel up using a configuration file to map requests to response data files but in the app there is a config file which is requested on launch and contains lists of various endpoints for the app to use. I am calling the mock setup immediately after calling app.launchTunnel() but because app.launchTunnel() waits for a response from the application under test so the mock setup is occurring too late to intercept the config call.

**Comment by tcamin** [comment]
Check (this)[https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md#launch-with-options-and-startupblock]. What is executed in the `startupBlock` is executed before the app enters the `appDidFinishLoading`. I  will update the documentation to make this more clear.
