### ISSUE TITLE
Assertion failure on Travis CI...

### ISSUE THREAD

**Issue by jfehr67** [Subito-it/SBTUITestTunnel#33]
Running on Travis CI, occasionally I get a timeout when starting the server. Is it possible to change the hard-coded 30 seconds to something user configurable? Or could there be some other reason its failing?

2017-06-05 21:29:55.521 XCTRunner[10943:32296] *** Assertion failure in -[SBTUITunneledApplication waitForServerUp], <app>/Pods/SBTUITestTunnel/Pod/Client/SBTUITunneledApplication.m:154
2017-06-05 21:29:55.524 XCTRunner[10943:32296] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '[SBTUITestTunnel] failed to connect to client app.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010952ab0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000108f8f141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010952ecf2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000108b293b6 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   SBTUITestTunnel                     0x000000011f17e9a4 -[SBTUITunneledApplication waitForServerUp] + 356
	5   SBTUITestTunnel                     0x000000011f17e5d3 __65-[SBTUITunneledApplication launchTunnelWithOptions:startupBlock:]_block_invoke + 67
	6   libdispatch.dylib                   0x000000010c648585 _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x000000010c669792 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x000000010c65168b _dispatch_root_queue_drain + 287
	9   libdispatch.dylib                   0x000000010c65150d _dispatch_worker_thread3 + 113
	10  libsystem_pthread.dylib             0x000000010cad3616 _pthread_wqthread + 1299
	11  libsystem_pthread.dylib             0x000000010cad30f1 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by tcamin** [comment]
I just released version 2.1.0 which allows to change the connection timeout.

Just call `SBTUITunneledApplication.setConnectionTimeout(60)` before launching your test.

We had all sorts of issues running UI tests from Travis, so I'm unsure this will actually help but please report back if this somehow works for you.
