### ISSUE TITLE
CURL support

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#34]
A nice feature to have is the ability to make CURL requests to SBT to mock networks responses an example where this would be useful is when running tests with appium or other frameworks.

**Comment by tcamin** [comment]
Could you elaborate a scenario with some examples?

**Comment by Ashraf-Ali-aa** [comment]
currently there isn't a very good tools to mock network requests when using appium automation framework, sbt is really good but there is not way to control it from 3rd party framework / languages, if sbt supported modifying mocks via curl or an json api people can create custom libraries to control sbt

**Comment by tcamin** [comment]
I understand the use case, however it’s not something that I can implement atm
