### ISSUE TITLE
(SBTRequestMatch) For POST requests, query parameter is not functioning properly

### ISSUE THREAD

**Issue by juliancmg** [Subito-it/SBTUITestTunnel#35]
When setting up an SBTRequestMatch object, the query parameter will not be taken into account when monitoring for POST requests. 

For example:
`let matchCriteria = SBTRequestMatch.init(url: "https://api.segment.io/v1/batch", query: ["THISDOESNOTEXIST"], method: "POST")`

`let matchCriteria = SBTRequestMatch.init(url: "https://api.segment.io/v1/batch", query: ["THISEXISTS"], method: "POST")`

Both of these will return the same number of matches for requests. It doesn't seem to matter what is entered as the query parameter.

The only thing that succeeds (in failing) is modifying the URL or the method.

**Comment by juliancmg** [comment]
Any help would be super appreciated!

**Comment by tcamin** [comment]
Please provide a sample of full URLs, including at least the significant part of the body of the requests you'd expect to be matched/not matched.

**Comment by grigorye** [comment]
I've just faced this very issue in the sense that query does not work as I expected - i.e. I wanted to match *query* in POST request, but it did not work. But the thing is that it's actually documented, e.g. here (see quote below): https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md#sbtrequestmatch

> You can specify a regex on the URL, multiple regex on the query (**in POST and PUT requests they will match against the body**) and HTTP method using one of the several class methods available.

I wonder if there's rationale behind this decision? It looks like a missing functionality then?

Below is the relevant part of the code that ignores the query in case of POST and matching against the body instead.

https://github.com/Subito-it/SBTUITestTunnel/blob/master/Pod/Common/NSURLRequest%2BSBTUITestTunnelMatch.m#L48-L56

**Comment by tcamin** [comment]
Hi, thanks for the feedback. This indeed was wrong and should be fixed in https://github.com/Subito-it/SBTUITestTunnel/commit/22ca82e03cb1a3d62cde498f649e8012cf65768e

**Comment by grigorye** [comment]
@tcamin Will you update the documentation (Usage.md) as well?

**Comment by tcamin** [comment]
Of course I forgot, done!
