### ISSUE TITLE
change host url

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#36]
Is it possible to start SBTUITestTunnel on a specific ip address and port number rather than using localhost url endpoint,  I wanted to use charles proxy to intercept the network requests for debugging purposes and not have to set the proxy in system settings. The way I envisioned this working is have 2 modes one the standard SBTUITestTunnel mock feature and the other is passing in a argument or setting in user defaults ip address and port of a proxy server and when you start the app SBTUITestTunnel forward the network requests to the specified ip address but if you run the ui tests it defaults back to the default the standard localhost.

**Comment by tcamin** [comment]
This might be addable as per https://stackoverflow.com/questions/28101582/how-to-programmatically-add-a-proxy-to-an-nsurlsession
