### ISSUE TITLE
Mock HTTP method

### ISSUE THREAD

**Issue by hejhj** [Subito-it/SBTUITestTunnel#4]
Hi, these methods don’t say where I can specify HTTP request method:
stubRequestsWithRegex
stubRequestsWithQueryParams
If I want to mock a request with POST/GET/DELETE... method, how can I do that?

**Comment by tcamin** [comment]
I've just released an update of the library which allows you to separately specify whether to stub network requests based on the URL, query parameters (or body for POSTs and PUTs) and HTTP method by introducing a new class `SBTRequestMatch`. Check the documentation and/or the UI Tests you find in the example project.

Let me know if this works for you so I can close the issue.

**Comment by hejhj** [comment]
Thanks Tomas, it's working nicely.
