### ISSUE TITLE
Simulate no internet connection

### ISSUE THREAD

**Issue by alexs555** [Subito-it/SBTUITestTunnel#44]
Is it possible to simulate no internet connection with SBTUITestTunnel in XCUITests? 
(Use case: during test execution I need to turn internet off, make several asserts, than turn it back on and make several asserts)
If so, where can I found relevant code or docs?
thx!

**Comment by tcamin** [comment]
Hi there, mocking no network isn’t as easy as it sounds. I’ll add this to my todo list and will definitely implement it if doable.
