### ISSUE TITLE
any way to turn on stubbing in non-tests? ie. during development?

### ISSUE THREAD

**Issue by jonchui** [Subito-it/SBTUITestTunnel#45]
usecase: 
- when developers haven't finished API backends (or they're in flux) and i just want to use dummy data

**Comment by tcamin** [comment]
I’d definitely advise you to use Charles (https://www.charlesproxy.com/) for that. It’s extremely powerful and flexible.

**Comment by jonchui** [comment]
love charles, but i didn't know i can easily stub things out?
ᐧ

Jon Chui | YwamKona.org | http://jonchui.com | @jonchui
<http://twitter.com/jonchui>


life verse: Matt 13:44 | our family blog @ vickiandjon.com  | ping me if
you have exciting freelancing projects ;) | 424-241-2484

**Comment by jonchui** [comment]
For the future, the ability to stub out requests is called "Map Local"

http://www.testeffective.com/better-mobile-app-testing-with-charles-proxy/#Map_Local
