### ISSUE TITLE
 rewrite network response

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#47]
Hi @tcamin is it possible to intercept a response request from a remote server and partially rewrite the response i.e 

remote server:
```
{
    "time-epoch": "1519119705",
    "country": "GB"
}
``` 
Partial rewite  
replace GB to IT
```
{
    "time-epoch": "1519119705",
    "country": "IT"
}
```

**Comment by tcamin** [comment]
Unfortunately we’re currently missing a “rewrite feature”, however I’m wondering if you really can’t stub a request like the one in your example.

**Comment by Ashraf-Ali-aa** [comment]
@tcamin if I didn't have to mock out the epoch time then yes stubbing would have worked but the application I am testing is time sensitive and if the time is out by a couple of seconds the application would not work, SBT already ready has a monitoring mode I was thinking if there was a way modify the response while intercepting the network.

**Comment by tcamin** [comment]
Ok, I understand. 

Unfortunately the rewrite feature is rather broad (just as an example checkout Charle's rewrite feature) and anything but trivial to add, but I definitely consider it for the future. 👍🏻

**Comment by tcamin** [comment]
Hi there, good news for you, I managed to add the rewrite feature 🚀

See the documentation (https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md#rewrite) and example project (`RewriteTests.swift`) to find out how to use it.

**Comment by Ashraf-Ali-aa** [comment]
excellent work 👍
