### ISSUE TITLE
SBTUITestTunnel and Carthage

### ISSUE THREAD

**Issue by tomaszmnich** [Subito-it/SBTUITestTunnel#48]
Can you make SBTUITestTunnel to be available to install through the Carthage?

**Comment by tcamin** [comment]
That would be nice, could you help adding support for this?

**Comment by tomaszmnich** [comment]
Since I don't know the project's architecture it's gonna be hard, but I'm ready to help.

**Comment by tomaszmnich** [comment]
Since there is no feedback I'm trying to build SBTUTestTunnel as a Carthage framework. Could you help me and point out which project's files are necessary to be added to `Build Phases -> Compile Sources` in the new created framework scheme?

**Comment by tcamin** [comment]
You can check that from the podspec. There should be basically 2 frameworks, one containing files that will be added to the application’s target (together with the GCDWebServer dependency) and the other to the UI test target.

The files that go in the application framework are under Source/Server, the ones that go in the UI testing target are under Source/Client. Additionally the files under Source/Common go in both frameworks.

HTH, however you should find everything you need in the example project in the repo.

**Comment by tcamin** [comment]
Gonna close this for now.
