### ISSUE TITLE
returnJsonNamed should support looking for json files at different places

### ISSUE THREAD

**Issue by hejhj** [Subito-it/SBTUITestTunnel#5]
And when I try to use app.stubRequestsWithRegex("(.*)someurl(.*)", returnJsonNamed: "test.json", returnCode: 200, responseTime: SBTUITunnelStubsDownloadSpeed3G)
It turns out json file has to be at the same directory as tests.

**Comment by tcamin** [comment]
As far as I can tell the mocking files do not need to be in any particular path as long as they:

- are in the UI Test Target
- the folder that contains the mock data is added as a 'Group' (and not as a folder reference)

**Comment by hejhj** [comment]
You're right. I just added a new Group and it's working.
