### ISSUE TITLE
app.launchTunnel() unrecognized selector sent to instance

### ISSUE THREAD

**Issue by jibeex** [Subito-it/SBTUITestTunnel#50]
Hello, I am using cocoapods to integrate this lib into my project. There is no problem on building, but when the test target is being executed, "unrecognized selector sent to instance" is reported on calling "app.launchTunnel()". It seems that the 'app' from the Objective-C category isn't loaded correctly. Do you have any idea how to resolve this issue ?

X-Code: Version 9.2 (9C40b)
Cocoapods: 1.3.1
SBTUITestTunnel: 3.0.4

**Comment by tcamin** [comment]
You're probably instantiating `let app = XCUIApplication` before calling launchTunnel().

As stated in the [docs](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md#launch-with-no-options) you do not need to do this when using SBTUITestTunnel.

**Comment by jibeex** [comment]
Following your suggestion, I have just removed all the places where I instantiate XCUIApplication manually. But Still got the same error.

**Comment by jibeex** [comment]
I have the impression that the integration with Cocoapods is not working.

`target 'Univadis UITests' do
    pod 'SBTUITestTunnel/Client'
end`

I cannot even reference *SBTStubResponse*.

  "_OBJC_CLASS_$_SBTStubResponse", referenced from:

**Comment by tcamin** [comment]
Are you sure that the name of the *target* is correct?

**Comment by jibeex** [comment]
It used to work correctly. Just from this week it doesn't work. May be caused by some updates. The target name is correct. I can see the auto generated build phases "Embeded Pods Frameworks"

**Comment by jibeex** [comment]
In the ui test runner.app, I cannot find SBTUITestTunnel framework. That may be not normal.

<img width="593" alt="screen shot 2018-03-28 at 6 27 09 pm" src="https://user-images.githubusercontent.com/3897461/38042836-b21bd346-32b5-11e8-9208-6dd8e11f4604.png">
<img width="347" alt="screen shot 2018-03-28 at 6 27 18 pm" src="https://user-images.githubusercontent.com/3897461/38042842-b52f1ae8-32b5-11e8-82dc-8d12461176c6.png">

**Comment by tcamin** [comment]
Again I’m pretty sure the target name should be target 'Univadis_UITests’ with underscore

**Comment by jibeex** [comment]
In .xctest, the framework folder empty.

<img width="464" alt="screen shot 2018-03-28 at 6 29 23 pm" src="https://user-images.githubusercontent.com/3897461/38042974-0fdaeb84-32b6-11e8-8a02-db758aa2e093.png">
<img width="564" alt="screen shot 2018-03-28 at 6 29 38 pm" src="https://user-images.githubusercontent.com/3897461/38042977-11deccfc-32b6-11e8-9a52-75f125dd4edc.png">

**Comment by tcamin** [comment]
Again I’m pretty sure the target name should be target 'Univadis_UITests’ with underscore.

When you do pod install you should see both the client and the server being installed

**Comment by jibeex** [comment]
I test by renaming the target to Univadis_UITests and making the same change on the podfile. But it doesn't make it better.

**Comment by jibeex** [comment]
That is what I see when I do  *pod install*

`pod install
Analyzing dependencies
Downloading dependencies
Using 1PasswordExtension (1.8.4)
Using AppsFlyerFramework (4.8.1)
Using Appsee (2.3.6)
Using AssistantKit (0.4.1)
Using BBBadgeBarButtonItem (1.2)
Using Bolts (1.8.4)
Using Brightcove-Player-Core (6.1.4)
Using CHIPageControl (0.1.3)
Using Crashlytics (3.9.3)
Using FBSDKCoreKit (4.28.0)
Using Fabric (1.7.2)
Using GCDWebServer (3.4.2)
Using GoogleAnalytics (3.17.0)
Using GoogleConversionTracking (3.4.0)
Using GoogleTagManager (3.15.2)
Using JB4ASDK (4.9.6)
Using OCMock (3.4.1)
Using Reflection (0.15.0)
Using SBTUITestTunnel (3.0.4)
Using SpinKit (1.2.0)
Using SwiftKVC (4.0.0)
Using SwiftLint (0.24.0)
Using UPCarouselFlowLayout (1.1.1)
Using uservoice-iphone-sdk (3.2.12)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 21 dependencies from the Podfile and 24 total pods installed.`

**Comment by tcamin** [comment]
I'd suggest you to check the Example project to see how it's being integrated.

**Comment by jibeex** [comment]
Hi, finally I have it fixed today by adding the following script in the podfile

```if config.name == 'Debug preprod' or config.name == 'Debug alpha'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ENABLE_UITUNNEL=1']
            end```

**Comment by tcamin** [comment]
Please take extra precautions and make sure you’re not shipping the tunnel in production.

**Comment by jibeex** [comment]
I have checked and those flags were added at the beginning. I think they are then removed by during some merging process.
