### ISSUE TITLE
SBT crashes when clearing `userDefaults`

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#51]
@tcamin Hi, I am the latest SBT library (3.0.5) the app crashes when I clear user-default like this `app.userDefaultsReset()`

![47ffe3cb-186f-4427-a586-8cbdb527dac2](https://user-images.githubusercontent.com/7900956/38891163-6794d69e-427b-11e8-977d-3cf5ffe29274.jpg)

**Comment by tcamin** [comment]
This should have been fixed in 3.0.5. Have you tried cleaning your derived data’s?

**Comment by Ashraf-Ali-aa** [comment]
@tcamin yes, I even removed the pod and did a fresh install.

**Comment by tcamin** [comment]
Try with 3.0.6

**Comment by Ashraf-Ali-aa** [comment]
thanks its working now
