### ISSUE TITLE
[NSInternalInconsistencyException] Failed waiting app to be ready

### ISSUE THREAD

**Issue by alter-al** [Subito-it/SBTUITestTunnel#52]
Hello, I am using SBTUITestTunnel v3.0.6 and I have a question, can I stubb requests in app running via bundle_id?

Example, if I run app with bundle:

       app = SBTUITunneledApplication(bundleIdentifier: "com.my.app")
       app.launchTunnel // >> NSInternalInconsistencyException

I have NSInternalInconsistencyException: 

    [SBTUITestTunnel] Failed waiting app to be ready

**Comment by tcamin** [comment]
I guess that's not possible, what is your use case?
Does `com.my.app` launch the sbtuitesttunnel server side (does it call `SBTUITestTunnelServer.takeOff()`)?
