### ISSUE TITLE
Issue when building on real devices while in SBTUITunnel framework

### ISSUE THREAD

**Issue by Aya-Akl** [Subito-it/SBTUITestTunnel#54]
Hi there,

although I did the setup correctly and completely as per the documentation, the error below is always displaying:
```
ld: ‘/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest’ does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file ‘/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest’ for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

- I cleaned the project
- I added the preprocessor macros
- I wrapped the code inside App delegate with #IF #DEBUG
- The one difference is that the App code is in Objective-C not swift but I don't think this should matter, however the tests are written in Swift.

Please help me as this is a Blocker for me.

Thanks in advance!

**Comment by tcamin** [comment]
Try disabling bitcode for the UI Test target

**Comment by Aya-Akl** [comment]
Thanks a lot! 
I did it and it is working fine now.
