### ISSUE TITLE
Regex wildcard

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#58]
Hi is it possible to get the wildcard string value from a SBTRequestMatch request i.e  `SBTRequestMatch.url("myhost.com/v1/user/.*/info",` should retrun the value from `.*`

**Comment by francybiga** [comment]
If I correctly understand you would like to have a "capturing group" support for SBTRequest match.

`SBTRequestMatch` is a class which does not represent an actual match of a string, instead it represents a pattern which can be passed to the library's functions `monitor`, `stub` and others.

So the capturing group support should be provided as return value from the `matches` method (which is mainly used internally by library's networking functionalities) or, alternatively, directly by the `monitor` function (or `stub` or others which take `SBTRequestMatch` as parameter).

It would be an overhead to propagate this information up to the calling code and  also that would make the API more complex for a for a fairly limited use-case.

However I think you can achieve quite the same behaviour by monitoring request passing the `SBTRequestMatch` and then retrieving the monitoredRequests (using `peek` or `flush`) and access the url components directly from each request.

For example:
```   
 app.monitorRequests(SBTRequestMatch.url("myhost.com/v1/user/.*/info"))

    // do stuff which causes some network calls to happen

    let matches = app.monitoredRequestsFlushAll()
    for match in matches {
        let matchedUrl = match.originalRequest?.URL
        // Use NSURLComponents or others to get the url component you need
    }
```

Does this make sense to you?
