### ISSUE TITLE
App random crash in function takeOff() when launch app in UIAutomation

### ISSUE THREAD

**Issue by liweiran10086** [Subito-it/SBTUITestTunnel#62]
This is a random crash and it's similator to https://github.com/Subito-it/SBTUITestTunnel/issues/37 , but we are not using Cucumber, just using basic XCTest
<img width="1608" alt="default" src="https://user-images.githubusercontent.com/44474610/50081065-7ff1a100-0228-11e9-9abf-c56752f5d6a4.png">

**Comment by tcamin** [comment]
If you're able to provide a demo project that exhibits the problem it would help to try to fix the issue. The provided informations are not enough to debug the issue.
