### ISSUE TITLE
Launching App fails in 3.1.0 

### ISSUE THREAD

**Issue by rfodge** [Subito-it/SBTUITestTunnel#64]
I just upgraded from 3.0.14 to 3.1.0 and now I'm unable to launch the application.  It gives me the following error:
<img width="991" alt="screen shot 2019-01-16 at 11 39 41 am" src="https://user-images.githubusercontent.com/11653643/51264148-d0713100-1983-11e9-9aa0-27614866fa69.png">

Can you tell me what changed with regards to launching the application in the 3.1.0 release?

**Comment by tcamin** [comment]
Do test run if you downgrade again to 3.0.14?

**Comment by rfodge** [comment]
Yeah, 3.0.14 works for me.

**Comment by rfodge** [comment]
> Yeah, 3.0.14 works for me. I am using Xcode 10. I am going to try Xcode 9.4 today to see if that makes any difference.   

And yeah, I tried 3.1.0 and 3.1.4 but get that result for both.

**Comment by rfodge** [comment]
Same issue when I try to upgrade to 3.1.x using 9.4.1 of Xcode.

**Comment by tcamin** [comment]
Can you reproduce the issue on an a blank project with Xcode 10.1. We're heavily using the tunnel on a large project with a lots of tests without any problem using Xcode 10.1.
