### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by jonnydangerous** [Subito-it/SBTUITestTunnel#65]
If I try to use SBTUITestTunnelServer.registerCustomCommandNamed and return an instance of a class I get the following error. 

2019-02-06 15:25:02.469071-0700 WarmFuzzies2[21854:6688315] -[WarmFuzzies2.TestRealm encodeWithCoder:]: unrecognized selector sent to instance 0x6000010bfdd0
2019-02-06 15:25:02.470054-0700 WarmFuzzies2[21854:6688315] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[WarmFuzzies2.TestRealm encodeWithCoder:]: unrecognized selector sent to instance 0x6000010bfdd0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104a4a1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000103fe8735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104a68f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000104a4eed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x0000000104a50da8 _CF_forwarding_prep_0 + 120
	5   Foundation                          0x0000000103a2f175 _encodeObject + 1230
	6   Foundation                          0x0000000103a2e22e +[NSKeyedArchiver archivedDataWithRootObject:] + 156
	7   WarmFuzzies2                        0x0000000101f41f35 -[SBTUITestTunnelServer processCustomCommandIfNecessary:returnObject:] + 725
	8   WarmFuzzies2                        0x0000000101f417e8 __36-[SBTUITestTunnelServer takeOffOnce]_block_invoke.54 + 264
	9   libdispatch.dylib                   0x000000010647f4e1 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x000000010648054b _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010648701c _dispatch_lane_serial_drain + 720
	12  libdispatch.dylib                   0x0000000106487b5f _dispatch_lane_invoke + 401
	13  libdispatch.dylib                   0x00000001064909a8 _dispatch_workloop_worker_thread + 645
	14  libsystem_pthread.dylib             0x000000010686a60b _pthread_wqthread + 409
	15  libsystem_pthread.dylib             0x000000010686a405 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

According to the documentation I am supposed to be able to return any object rom that registered command, I have also tried calling  app.performCustomCommandNamed passing my own injected class and I get a very similar error around the NSKeyedArchiver while it seems to be encoding or decoding the injected or return object.

My use case is that my app that I need to test does a lot of very complicated web service calls and gets a lot of json responses. However my app listens and updates based on those responses being saved to a realm database. 

I want to stub/replace the app's version of realm with one I inject from the UITest or I want to be able to get a handle on the realm instance used by the app in the UI test so I can update realm which causes my UI to update based on the realm database changes. Does this project allow for this to happen or am I going beyond the scope of this project?

**Comment by tcamin** [comment]
Documentation wasn’t 100% correct. You can pass any object as long as it conforms to NSCoding. If you need to replace your database you could alternatively inject it by uploading a prebacked test database. Would that work?
