### ISSUE TITLE
Startup Block Not Called

### ISSUE THREAD

**Issue by charleshberlin** [Subito-it/SBTUITestTunnel#68]
XCode 10.2.1
Deployment Target 11.0
Pod Version 3.2.1
Running Tests on 12.2 Simulator

When running UI Tests, the startup block parameter in launchTunnel is never called

**Comment by tcamin** [comment]
Are you calling `SBTUITestTunnelServer.takeOff()` in appDidFinishLaunching? See https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Setup.md#application-target
