### ISSUE TITLE
Multiple commands produce Error

### ISSUE THREAD

**Issue by kobi963** [Subito-it/SBTUITestTunnel#69]
Hi!
I'm using your product via cocoapods and this is the error that I'm getting.
Thanks a lot for a great product!
As you can see in the link below the error appeared in xcode 10 new build system update that apple made:
https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce

I don't want to use the legacy workaround and I tried all of the suggested solutions.

The error from my build:
```

✗ Multiple commands produce '/tmp/sandbox/57b2e1102d158c01000b31e9/bbbuild/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework/SBTUITestTunnel':
77
    » 1) Target 'SBTUITestTunnel-Client' has a command with output '/tmp/sandbox/57b2e1102d158c01000b31e9/bbbuild/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework/SBTUITestTunnel'
78
    » 2) Target 'SBTUITestTunnel-Server' has a command with output '/tmp/sandbox/57b2e1102d158c01000b31e9/bbbuild/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework/SBTUITestTunnel'
```

podfile:
```

platform :ios, '9.3'

workspace 'MyAppName'

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'TestApp' do
    use_frameworks!
    project 'TestApp.xcodeproj'
    pod 'SBTUITestTunnel/Server'
    pod 'BlocksKit'
    
    target 'TestAppUITests' do
      use_frameworks!
      project 'TestApp.xcodeproj'
      pod 'SBTUITestTunnel/Client'
      pod 'BlocksKit'
    end
end

target 'TestAppDebug' do
    use_frameworks!
    project 'TestApp.xcodeproj'
    pod 'SBTUITestTunnel/Server'
    pod 'BlocksKit'
end

target 'TestAppDebugUITests' do
    use_frameworks!
    project 'TestApp.xcodeproj'
    pod 'SBTUITestTunnel/Client'
    pod 'BlocksKit'
    testing_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['SDKROOT'] = 'iphoneos'
            config.build_settings['ARCHS'] = 'armv7', 'armv7s', 'arm64'
        end
        
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['SDKROOT'] = 'iphoneos'
            config.build_settings['ARCHS'] = 'armv7', 'armv7s', 'arm64'
        end
    end
end


```
apple suggestion of how to solve this error:
https://help.apple.com/xcode/mac/current/#/dev14a2fd0c0

please let me know if you need extra data.

Thanks,
Kobi

**Comment by tcamin** [comment]
Unlike unit test targets for UI tests (and to properly used SBTUITestTunnel) you shouldn't nest 'TestAppUITests' inside your 'TestApp' target. The problem is that 'SBTUITestTunnel/Server' and 'SBTUITestTunnel/Client' both produce a framework with the same name, and you're importing both those subspecs in 'TestAppUITests'.

Splitting them as you did with 'TestAppDebug' and 'TestAppDebugUITests' should most likely work.

**Comment by kobi963** [comment]
Hi Tomas!
thanks for your input, I tried what you suggested and it still the same: 

### **The error:**
 ```
error: Multiple commands produce
'/Users/kobi.oren/Library/Developer/Xcode/DerivedData/BioCatchSDK-bakzhytjfizwbfggcffbmgwqwtmn/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework':
1) Target 'SBTUITestTunnel-Client' has create directory command with output '/Users/kobi.oren/Library/Developer/Xcode/DerivedData/BioCatchSDK-bakzhytjfizwbfggcffbmgwqwtmn/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework'
2) Target 'SBTUITestTunnel-Server' has create directory command with output '/Users/kobi.oren/Library/Developer/Xcode/DerivedData/BioCatchSDK-bakzhytjfizwbfggcffbmgwqwtmn/Build/Intermediates.noindex/ArchiveIntermediates/TestApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SBTUITestTunnel.framework'
```


### **the pod file after the suggested change:**
```
platform :ios, '9.3'

workspace 'BioCatchSDK'

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'TestApp' do
    use_frameworks!
    project 'TestApp.xcodeproj'
    pod 'SBTUITestTunnel/Server'
    pod 'BlocksKit'
end

target 'TestAppUITests' do
  use_frameworks!
  project 'TestApp.xcodeproj'
  pod 'SBTUITestTunnel/Client'
  pod 'BlocksKit'
end
#    pod 'WebViewJavascriptBridge', '~> 6.0'

target 'TestAppDebug' do
    use_frameworks!
    project 'TestApp.xcodeproj'
    pod 'SBTUITestTunnel/Server'
    pod 'BlocksKit'
    #    pod 'WebViewJavascriptBridge', '~> 6.0'
end

target 'TestAppDebugUITests' do
    use_frameworks!
    project 'TestApp.xcodeproj'
    pod 'SBTUITestTunnel/Client'
    pod 'BlocksKit'
    testing_pods
end

target 'TestAppObjC' do
    use_frameworks!
    project 'TestAppObjC/TestAppObjC.xcodeproj'
    pod 'SBTUITestTunnel/Server'
    pod 'BlocksKit'
end

target 'TestAppObjCUITests' do
    use_frameworks!
    project 'TestAppObjC/TestAppObjC.xcodeproj'
    pod 'SBTUITestTunnel/Client'
    pod 'BlocksKit'
end

target 'TestAppObjCTests' do
    use_frameworks!
    project 'TestAppObjC/TestAppObjC.xcodeproj'
    pod 'SBTUITestTunnel/Client'
end

target 'BioCatchSDKTests' do
    use_frameworks!
    project 'BioCatchSDK.xcodeproj'
    pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
    pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too
    pod 'Cuckoo'
    testing_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        installer.pods_project.build_configurations.each do |config|
            
            #             set bit code to NO for all builds because it caused problems with xcode 8.3.2. The framework built for production is built with bitcode and checks that it is included, so that shouldn't be a problem
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['SDKROOT'] = 'iphoneos'
            config.build_settings['ARCHS'] = 'armv7', 'armv7s', 'arm64'
        end
        
        target.build_configurations.each do |config|
            
            #             set bit code to NO for all builds because it caused problems with xcode 8.3.2. The framework built for production is built with bitcode and checks that it is included, so that shouldn't be a problem
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['SDKROOT'] = 'iphoneos'
            config.build_settings['ARCHS'] = 'armv7', 'armv7s', 'arm64'
        end
    end
end

```

**Comment by tcamin** [comment]
You cleaned derived data, right?

**Comment by kobi963** [comment]
yes, deleted all derived data folder before doing archive.

**Comment by tcamin** [comment]
😞 I was pretty confident the suggestion would solve the problem. Unfortunately this sounds more a Xcode/CocoaPods issue than a SBTUITestTunnel one. Please ping back if you manage to solve the issue as it might be useful for someone else as well

**Comment by kobi963** [comment]
Will do! Thanks for your help.

**Comment by tcamin** [comment]
Hey, it seems this is

**Comment by maios** [comment]
AFAIK this is still an ongoing issue with XCode 10.2.1, it seems to be XCode/CocoaPods bug, here is the [OpenRadar](https://openradar.appspot.com/radar?id=5038526135533568)
I have found a couple of ways to bypass this:
1. Switch to Legacy Build System. I'm not a fan of this, also [this](https://github.com/CocoaPods/CocoaPods/issues/8206#issuecomment-451686995) pointed out that the new archive failure might be a good thing.
2. Not integrate SBTUITestTunnel for schemes used in archive, for example we run UI Tests in Debug, so we specify in Podfile for `SBTUITestTunnel` to only be integrated in Debug mode, in our project this is a safe way, since we only build archive in Release mode, however, this might not be ideal for others.
```
target 'MyApp' do
  pod 'SBTUITestTunnel/Server', :configurations => ["Debug"]
end

target 'MyAppUITests' do
  pod 'SBTUITestTunnel/Client', :configurations => ["Debug"]
end
```
3. Telling CocoaPods to remove `SBTUITestTunnel/Client` target from the Pods project in `post_install`
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'SBTUITestTunnel/Client'
      target.remove_from_project
    end
  end
end
```
This will remove `SBTUITestTunnel/Client` from Pods project, thus, there won't be duplicated framework created by both subspecs in Products list -> archive should succeed.

**Comment by navartis** [comment]
> AFAIK this is still an ongoing issue with XCode 10.2.1, it seems to be XCode/CocoaPods bug, here is the [OpenRadar](https://openradar.appspot.com/radar?id=5038526135533568)
> I have found a couple of ways to bypass this:
> 
> 1. Switch to Legacy Build System. I'm not a fan of this, also [this](https://github.com/CocoaPods/CocoaPods/issues/8206#issuecomment-451686995) pointed out that the new archive failure might be a good thing.
> 2. Not integrate SBTUITestTunnel for schemes used in archive, for example we run UI Tests in Debug, so we specify in Podfile for `SBTUITestTunnel` to only be integrated in Debug mode, in our project this is a safe way, since we only build archive in Release mode, however, this might not be ideal for others.
> 
> ```
> target 'MyApp' do
>   pod 'SBTUITestTunnel/Server', :configurations => ["Debug"]
> end
> 
> target 'MyAppUITests' do
>   pod 'SBTUITestTunnel/Client', :configurations => ["Debug"]
> end
> ```
> 
> 1. Telling CocoaPods to remove `SBTUITestTunnel/Client` target from the Pods project in `post_install`
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     if target.name == 'SBTUITestTunnel/Client'
>       target.remove_from_project
>     end
>   end
> end
> ```
> 
> This will remove `SBTUITestTunnel/Client` from Pods project, thus, there won't be duplicated framework created by both subspecs in Products list -> archive should succeed.

This receipts does not work.
Here it is pull request that fixes this issue: https://github.com/Subito-it/SBTUITestTunnel/pull/81
