### ISSUE TITLE
Multiple commands produce error when archive

### ISSUE THREAD

**Issue by liweiran10086** [Subito-it/SBTUITestTunnel#71]
It's the same problem with https://github.com/Subito-it/SBTUITestTunnel/issues/69

It only happens on Xcode10.2,

Here is an easy way to reproduce the error and It only fails when archive file.

1. Git clone this repo, open SBTUITestTunnel/Example/SBTUITestTunnel.xcworkspace
2. In Xcode , Select the device `Generic iOS Device`
3. Select the Product-> Archive (solve the provision profile/certificate problem first)

On Xcode10.0, it will build successfully.
<img width="935" alt="图片" src="https://user-images.githubusercontent.com/44474610/57275948-995d9180-70d2-11e9-9acc-14df64825de8.png">

But on Xcode 10.2, it will fail with the error
<img width="1790" alt="图片" src="https://user-images.githubusercontent.com/44474610/57276018-d3c72e80-70d2-11e9-8c55-50725159444c.png">

Can you fix this from your side, for example rename one of the framework to avoid duplicate output?

**Comment by tcamin** [comment]
I tried on Xcode 10.2.1 and it's working, did you try to update?

**Comment by haowang10** [comment]
me too~ try 3~5 archive to succeed
