### ISSUE TITLE
Stub not working

### ISSUE THREAD

**Issue by adamontherun** [Subito-it/SBTUITestTunnel#72]
[ShowMe.zip](https://github.com/Subito-it/SBTUITestTunnel/files/3190244/ShowMe.zip)

I've tried everything I could think of to get a simple stubbing example to work, and having no luck. This library is exactly what I need, but I'm just not having any luck. 

Xcode 10.2.1
Swift 5
Installed with Cocoapods
DEBUG=1

Any tips would be greatly appreciated. I've included the full sample project above and some screenshots below.

![Screen Shot 2019-05-16 at 9 01 03 PM](https://user-images.githubusercontent.com/466580/57909172-bbb38580-781d-11e9-8946-a34ddfb2d757.png)
![Screen Shot 2019-05-16 at 9 01 22 PM](https://user-images.githubusercontent.com/466580/57909196-cc63fb80-781d-11e9-8f3c-3afed53c6176.png)
![Screen Shot 2019-05-16 at 9 01 50 PM](https://user-images.githubusercontent.com/466580/57909215-d7b72700-781d-11e9-9cc5-a0c56bf60a03.png)
![Screen Shot 2019-05-16 at 9 02 15 PM](https://user-images.githubusercontent.com/466580/57909228-e7367000-781d-11e9-9077-c842f92736a8.png)
![Screen Shot 2019-05-16 at 9 03 03 PM](https://user-images.githubusercontent.com/466580/57909261-033a1180-781e-11e9-8329-796f7278b28c.png)
![Screen Shot 2019-05-16 at 9 03 38 PM](https://user-images.githubusercontent.com/466580/57909290-1cdb5900-781e-11e9-8a6a-986182b9bc40.png)

**Comment by tcamin** [comment]
Hi,

the problem in your code is that you're not handling asynchronous events.

The network request that fetches the json is done in `viewDidLoad()` of the initial view controller, which means it's done immediately at startup. You are setting the stub after app.launchTunnel() but at that moment the app might already have started and your stub won't be applied.

The second problem is related to XCTAsserts and asynchronous events (the label changes after the network call completes). On asynchronous event you should always use expectations.

To fix the first problem make sure to call everything that need be set before the app starts in the `laucnTunnel()` closure.

To fix the second problem use the helper method in the following XCTestCase extension.

<img width="951" alt="Screenshot 2019-05-17 at 11 26 16" src="https://user-images.githubusercontent.com/875025/57918211-957dfc00-7896-11e9-8a9d-99ce1c15fc89.png">

**Comment by adamontherun** [comment]
@tcamin thank you so much, this did the trick.
