### ISSUE TITLE
UITest build error

### ISSUE THREAD

**Issue by charleshberlin** [Subito-it/SBTUITestTunnel#76]
I've recently started getting a "No such module 'SBTUITestTunnel'" error message, exactly when I can't be sure because it actually works locally on my machine (so something must be cached) but doesn't on CI (bitrise).  I am able to reproduce it now by doing a clean checkout of the repo.

The interesting thing about it is that I am getting this warning right before it fails:

Target 'Pods-{PROJECT-NAME}-UITests' of project 'Pods' was rejected as an implicit dependency for 'Pods_{PROJECT-NAME}_UITests.framework' because its architectures 'arm64' didn't contain all required architectures 'armv7 arm64'

I updated cocoapods and did a pod update to version 3.5.1 and still no dice.

My guess is this is some sort of architecture mismatch but I'm unsure how to solve it, please advise.

**Comment by tcamin** [comment]
You may try with a ‘pod deintegrate; pod install’.

**Comment by charleshberlin** [comment]
Tried that just now and no luck, same error message.

Is there anymore information I can provide that might help debug the issue?

**Comment by tcamin** [comment]
This seems to be something related to a misconfiguration of CocoaPods rather than an issue with the tunnel. Did you give SO a look? This one looks very similar: https://stackoverflow.com/questions/44559621/project-pods-was-rejected-as-an-implicit-dependency-for-pods-framework-becau

**Comment by charleshberlin** [comment]
This turned out to be a couple of things that were build/cocoapod configuration problems that manifested themselves in errors in SBUITestTunnel.  This can be closed.
