### ISSUE TITLE
How to match a stub request based on json body type?

### ISSUE THREAD

**Issue by vamsidarbhamulla** [Subito-it/SBTUITestTunnel#77]
When setting an SBTRequestMatch based on params (URL, method and body as a single keyword/line string), the stub replaced the provided response successfully. 

However, Stub matching failed when body param is a JSON string. 
I tried using the body string as key=value format and it did not work. 

Can you provide an example on how to use a JSON body in SBTRequestMatch object creation? 

Thank you.

I have added a test to check json body from provided examples :
<img width="1241" alt="Screen Shot 2019-08-29 at 3 44 47 PM" src="https://user-images.githubusercontent.com/6055661/63981487-2490d780-ca74-11e9-9988-65cc79731e89.png">

**Comment by tcamin** [comment]
We use `NSRegularExpression` to match the HTTP body, which requires to escape curly braces, therefore you should use the following `SBTRequestMatch`:

`let requestMatch = SBTRequestMatch(url: "httpbin.org", query: [], method: "POST", body: #"\{ "key": "value" \}"#)`.

I've added your test to the test suite in case it is useful to others.

**Comment by vamsidarbhamulla** [comment]
Thanks for the quick response. I got it now. However, I'm wondering how do you use NSRegularExpression to match multiple JSON object key-value pairs? As it will not maintain any specific order. By the way, It's an awesome project and thanks for make it available on open-source.

**Comment by tcamin** [comment]
Matching multiple json key-values can be done with regular expressions, it's not a sbtuitesttunnel specific feature. See for example https://stackoverflow.com/questions/19412416/regex-match-multiple-unordered-words-in-a-string

**Comment by vamsidarbhamulla** [comment]
Thanks for the suggestion. This can be closed.
