### ISSUE TITLE
Add logging Info

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#78]
@tcamin Hi I was wondering would it be possible to log to console when the app is trying to making a network request when the URL is set to be intercepted by SBT, this would be useful when debugging since I normally would use Charles proxy to see if that app is behaving correctly.

**Comment by tcamin** [comment]
Hi, sorry for the late reply. This can already be done with the Console.app, simply filter using `[UITestTunnelServer]` as shown below

<img width="1411" alt="Screenshot 2019-09-18 at 16 09 22" src="https://user-images.githubusercontent.com/875025/65156233-0264f680-da2f-11e9-9a62-5991778ada09.png">

**Comment by JinW-Airwallex** [comment]
@tcamin sorry to bump this issue up but the console app no longer shows logs when stubbing a request.

**Comment by tcamin** [comment]
Since when is this happening?

**Comment by JinW-Airwallex** [comment]
@tcamin We only started to use this lib recently so I'm not too sure. Just found this while trying to debug some stubs.
