### ISSUE TITLE
Match Request Headers

### ISSUE THREAD

**Issue by rfodge** [Subito-it/SBTUITestTunnel#85]
Are you able to specify a request header to match on?

**Comment by tcamin** [comment]
Not yet 😀. I’ll look into it as soon as I have some little spare time. Do you want to elaborate a little more the usage scenarios?

**Comment by rfodge** [comment]
OK.  In our app we can view data for multiple people and when the calls are made, the only thing that is different (that distinguishes which user the data needs to be pulled for) is a header value.  So I can use the tunnel to make the first call but when I switch the context to another user and then the call is made again, I have to fall back to another stub server using WireMock because the tunnel would keep returning the same call to me (since I don't have a way to distinguish to say give me something different for this user).  

Does that help?  

Thanks.

**Comment by tcamin** [comment]
Good news! I've added support for request/response header matching on master.
