### ISSUE TITLE
Stub not being picked up on before app launch

### ISSUE THREAD

**Issue by rfodge** [Subito-it/SBTUITestTunnel#89]
Hi, 

We were on version 3.0.14 of the tunnel and working on upgrading to the latest version.  We had code where we stubbed data in the beforeLaunch.  On app launch, a call is made so we stubbed it out in the beforeLaunch by doing this:
`BaseTest.sbtApp?.launchTunnel(withOptions:
                [SBTUITunneledApplicationLaunchOptionResetFilesystem,
                 SBTUITunneledApplicationLaunchOptionDisableUITextFieldAutocomplete]) {
                    self.beforeLaunch()
            }
`

This code no longer works in the latest version of the tunnel.  It is now making the api call BEFORE the the stubbing happens (in self.beforeLaunch()) whereas in version 3.0.14, it would stub the call prior to having the api call on app launch.   

Can you let us know if something regarding this behavior has changed?

Thanks.

**Comment by tcamin** [comment]
Hi! Can you provide the implementation of `beforeLaunch()`? We are using the tunnel in a very large application where we prepare stubs before app launches and everything works as expected.

A part from minor API changes the only thing that pops to mind regards stubbing of WKWebViews which is no longer enabled by default. You must explicitly opt-in as described [here](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md#wkwebview-stubbing). Nothing else should have changed wrt stubbing.

**Comment by rfodge** [comment]
We just have this:
BaseTest.sbtApp?.stubRequests(matching: SBTRequestMatch(url: requestURL),
                              response: SBTStubResponse(response: json))

where requestURL is ".*.../..." - the URL we match on and json is the response of the call 

In 3.0.14, the call is stubbed then the app launches and the call is made. When using the latest version, for some reason it is launching the app first and then stubbing call that we pass in the beforeLaunch.

**Comment by rfodge** [comment]
As a note, we are using Swift 5.0 and not 5.1 yet.  Not sure if this could be the cause of the problem or not?   But just thought i'd mention that if you are using 5.1.  We should be moving to 5.1 over the next few months.
