### ISSUE TITLE
Unable to run tests on device

### ISSUE THREAD

**Issue by akshatk** [Subito-it/SBTUITestTunnel#95]
Hi, When I run tests on the simulartor, they pass. When I try running tests on a device I get the following error:

Assertion Failure: SomeTestCaseClass.swift:47: failed: caught "NSInternalInconsistencyException", "Failed waiting for app to be ready"

The tests do not run at all.

SBTUITestTunnelClient version: 6.2.0
SBTUITestTunnelCommon version: 6.2.0
SBTUITestTunnelServer version: 6.2.0
GCDWebServer: ~> 3.0

Installed via Cocoapods version 1.8.4

Xcode 11.3.1
iOS 13.3.1

**Comment by tcamin** [comment]
I tried running the tests in the Example project on a physical device and they all run correctly. Are you sure that `[SBTUITestTunnelServer takeOff]` is being properly called?

**Comment by akshatk** [comment]
Yes, the SBTUITestTunnelServer.takeOff() (Swift 5) is being properly called in app delegate but when I do so, the app stays stuck on the splash screen and after a minute I get an exception on the dispatch_once block in once.h and inside the takeOff method and the app crashes.

+ (void)takeOff
{
    static dispatch_once_t once;
    dispatch_once(&once, ^{ // **SIGABRT**
        [self.sharedInstance takeOffOnce];
    });
}

Here are the logs:
t =    36.24s             Setting up automation session
    t =    39.21s             Wait for myapp to idle
    t =    99.26s                 App event loop idle notification not received, will attempt to continue.
2020-04-27 04:00:08.952115+0530 myappUITests-Runner[6324:1177708] *** Assertion failure in -[SBTUITunneledApplication testTunnelClient:didShutdownWithError:], PathtoPods/Client/SBTUITunneledApplication.m:80
    t =   130.61s     Assertion Failure: myappTestCase.swift:47: failed: caught "NSInternalInconsistencyException", "Failed waiting for app to be ready"

This does not happen on simulator.

**Comment by tcamin** [comment]
Could you try running SBTUITestTunnel example project tests?
