### ISSUE TITLE
File missing : SBTUITestTunnelCommon/SBTUITestTunnelCommon-Swift.h 

### ISSUE THREAD

**Issue by kilyan-s** [Subito-it/SBTUITestTunnel#96]
Hi,

I've been trying to mock API call for UI Testing and found this library. Unfortunately I couldn't get it to work. 

I have install the library with CocoaPods. 
```
target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'InputMask'
  pod 'SBTUITestTunnelServer'
  pod 'GCDWebServer', :inhibit_warnings => true
end

target 'MyAppUITests' do
  pod 'SBTUITestTunnelClient'
end
```
I have setup the library in ```application didFinishLaunchingWithOptions```

And the created a new UI Test case but when I try to run my test I get this build error ```'SBTUITestTunnelCommon/SBTUITestTunnelCommon-Swift.h' file not found``` on the import line ```#import <SBTUITestTunnelCommon/SBTUITestTunnelCommon-Swift.h>``` in the file ```SBTUITestTunnelCommon/NSURLRequest+SBTUITestTunnelMatch.m```

I have the version 6.2.0 of this library.
Using Xcode 11.3.1 and Swift 5.0

Thanks for your help

**Comment by tcamin** [comment]
Could you try again with 6.3.0?

**Comment by kilyan-s** [comment]
Hi,
Weirdly I could not update to 6.3.0 two days ago. Just run a pod update and I know have v. 6.3.0 but I get the same error when I build on the file ```SBTUITestTunnelCommon/NSURLRequest+SBTUITestTunnelMatch.m``` on the line ```#import <SBTUITestTunnelCommon/SBTUITestTunnelCommon-Swift.h>```

**Comment by tcamin** [comment]
Try moving use_frameworks! out of the MyTarget target and put it at Podfile level.


```
use_frameworks!


target ‘MyApp’ do
   # Comment the next line if you don’t want to use dynamic frameworks
   .... 
```

**Comment by kilyan-s** [comment]
I can build without any error now. Thanks for your help !
