### ISSUE TITLE
Add the ability to customize SBTStubFailureResponse body

### ISSUE THREAD

**Issue by vfadc** [Subito-it/SBTUITestTunnel#97]
Hi there!
There are many APIs that contain a json body inside a failure response, somthing like
`{
		"reason": "WRONG_PASSWORD",
		"description": "wrong password"
	}
}`
So, it would be really useful to add the ability to customize **SBTStubFailureResponse**'s body.

I found that now `userInfo` of `NSError` is always `nil`.
I guess, it would be enough to set `userInfo` of `NSError` object with `objectForKey:RKObjectMapperErrorObjectsKey`.

**Comment by tcamin** [comment]
SBTStubFailureResponse's is to be used only when [special](https://developer.apple.com/documentation/foundation/urlerror) URLSession error mocking is required (notConnectedToInternet, clientCertificateRejected, etc). If you need to stub a standard use https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Usage.md#sbtstubresponse returning the appropriate http code and response body

**Comment by vfadc** [comment]
You're right.
I tried to use `SBTStubResponse` to stub a failure with body, but it didn't work as I expected, `userInfo` didn't have `RKObjectMapperErrorObjectsKey` key.
But I found a bug in my code that I didn't specify `contentType` of `SBTStubResponse`. So, now I set `contentType` and it works!
Sorry for bothering you and thanx for quick feedback.
